kartverket/regelrett

backend/application.properties
backend/src/main/kotlin/no/bekk/AirTableController.kt
backend/src/main/kotlin/no/bekk/Application.kt

URLs to Airtable in application.properties

URLs to airtable in separate file

---

frontend/be-compliant/src/App.css
frontend/be-compliant/src/App.test.tsx
frontend/be-compliant/src/App.tsx
frontend/be-compliant/src/answer/Answer.tsx
frontend/be-compliant/src/hooks/answersFetcher.ts
frontend/be-compliant/src/index.css
frontend/be-compliant/src/index.tsx
frontend/be-compliant/src/reportWebVitals.ts
frontend/be-compliant/src/setupTests.ts

We had a lot of "any"-types, which are now fixed.
I also ran prettier on the src-folder to get rid of unused imports, blank spaces etc

Add types to everything and run prettier on src

---

frontend/be-compliant/src/App.tsx
frontend/be-compliant/src/answer/Answer.tsx
frontend/be-compliant/src/hooks/answersFetcher.ts
frontend/be-compliant/src/questionRow/QuestionRow.tsx

Added a new table column with a status field that displays if a question has been answered or not. This pr also fetches answers from the API when a new answer is submitted to update the frontend with newly submitted answers.

Add status field

---

backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
frontend/be-compliant/src/App.tsx
frontend/be-compliant/src/Table.tsx
frontend/be-compliant/src/answer/Answer.tsx
frontend/be-compliant/src/questionRow/QuestionRow.tsx
frontend/be-compliant/src/utils/formatTime.ts

I added a field in the table that shows when the last answer was given. It is formatted such that it displays changes made today and yesterday with a custom string format. Otherwise it shows time and date in a Norwegian locale format. This should probably in the fututre be updated to support different timeformats and timezones etc. 
The image below shows the visual changes.

Add time field with formatted time

---

frontend/be-compliant/src/App.css
frontend/be-compliant/src/Table.tsx
frontend/be-compliant/src/questionRow/QuestionRow.tsx
frontend/be-compliant/src/questionRow/questionRow.css

Made some small changes to the table to make questions and answers bold, and IDs not wrap

Small table changes

---

frontend/be-compliant/src/components/answer/Answer.tsx

There was an error in the browser console saying that the selected attribute in the option component is deprecated. Solved by switching to value in Select component with a selectedAnswer useState.

Fix selected error by using select value instead of select in option

---

frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/components/table/Table.tsx

Removed ID field from table because it isn't necessary for the user to view.
Before:
After:

Remove ID field from table in GUI

---

frontend/be-compliant/.prettierrc.json
frontend/be-compliant/src/App.test.tsx
frontend/be-compliant/src/App.tsx
frontend/be-compliant/src/components/answer/Answer.tsx
frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/components/questionRow/questionRow.css
frontend/be-compliant/src/components/table/Table.tsx
frontend/be-compliant/src/hooks/answersFetcher.ts
frontend/be-compliant/src/index.css
frontend/be-compliant/src/index.tsx
frontend/be-compliant/src/reportWebVitals.ts
frontend/be-compliant/src/setupTests.ts
frontend/be-compliant/src/utils/formatTime.ts

Added a prettier config and ran it on all files.
If you have any other wishes than single quotes, tab width of 2, or any other settings, feel free to change it, this is just a suggestion 😄

Added prettier config

---

frontend/be-compliant/src/components/answer/Answer.tsx
frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/components/table/Table.tsx

To make sorting (and filtering?) easier, we can combine the data and answers to the same js object before rendering the questionrows.

Combine data and answer

---

frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/components/table/Table.tsx

Adds sorting by time and status. The sorting algorithm is starting to look as a mess, i will look into that later. To use the same sorting algorithm i had to check if the field is of type date and add handling for that.

Add sorting by time and status

---

frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/components/table/Table.tsx

Add a new column in table with the responsible team

Add responsible team

---

frontend/be-compliant/src/components/answer/Answer.tsx
frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/components/table/Table.tsx
frontend/be-compliant/src/components/tableFilter/TableFilter.tsx

This pr creates a filter component that is a select dropdown. This component is used to set active filters. Then the table handles the filter logic that filters the data based on the active filters.
Before:
After:

Add status filter

---

backend/src/main/kotlin/no/bekk/AirTableController.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt

Adds a specific endpoint per team to get metodeverk- and metadata for specific teams

Add endpoint per team

---

backend/src/main/kotlin/no/bekk/AirTableController.kt
backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt

To change the way we route in frontend, we needed to add a new endpoint where you could get specific answers belonging to the team.

Add new endpoints + backend logic

---

backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt

We had a bug where it would both update a row and add a new answer-row when answering a question

Fix bug where it would add AND update row

---

frontend/be-compliant/src/hooks/answersFetcher.ts
frontend/be-compliant/src/hooks/datafetcher.ts
frontend/be-compliant/src/pages/Table.tsx

Legger til en liten spinni boi mens vi venter på at nettverkskallene resolves

Add loading state

---

frontend/be-compliant/src/index.tsx

Add header to all pages

---

frontend/be-compliant/src/pages/FrontPage.tsx

Legger til Kartverket-header og litt mer styling på forsiden

Add header

---

frontend/be-compliant/src/hooks/datafetcher.ts

Use column name to get answers instead of ID

---

frontend/be-compliant/src/components/MobileTableView.tsx
frontend/be-compliant/src/pages/Table.tsx

Startpunkt for å gjøre tjenesten litt mer brukbar på mobil. Mangler fortsatt filter og litt annen info, men tenker det er greit å ta det puljevis.

Make site usable on mobile

---

frontend/be-compliant/src/components/tableActions/TableActions.tsx
frontend/be-compliant/src/components/tableStatistics/TableStatistics.tsx
frontend/be-compliant/src/pages/Table.tsx

Add a x out of y questions answered to each team page above the table. 
Before:
After:

Add statistics to team page

---

frontend/be-compliant/src/components/MobileFilter.tsx
frontend/be-compliant/src/components/MobileTableView.tsx
frontend/be-compliant/src/components/tableActions/TableFilter.tsx
frontend/be-compliant/src/pages/Table.tsx

Add filters to mobile

---

frontend/be-compliant/src/components/answer/Answer.tsx

Increase width of select element

---

frontend/be-compliant/src/pages/Table.tsx

Add header data to mobile view

---

frontend/be-compliant/src/components/Priority.tsx
frontend/be-compliant/src/components/questionRow/QuestionRow.tsx
frontend/be-compliant/src/pages/Table.tsx

Legger til fargekoding basert på Kartverkets `Tag`-komponent. De har ikke helt samme farger som i skissene, så prøvde meg på de her:

Add color coding

---

frontend/be-compliant/src/pages/Table.tsx

Dette gjør at vi ikke viser en spinner når vi avgir et svar og refetcher fra databasen

Don't show spinner when giving answers

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/configuration/ConfigureDatabase.kt
backend/src/main/kotlin/no/bekk/plugins/FlywayMigrate.kt
backend/src/main/resources/application.conf
compose.yaml
frontend/beCompliant/Dockerfile
frontend/beCompliant/src/index.css
frontend/beCompliant/vite.config.ts

After converting to Vite and running flyway migrations in the application start up phase, some changes had to be made to the application and docker configurations. With these changes the application should be able to be run both locally and using docker.

Add environment variables to config

---

frontend/beCompliant/src/pages/Table.tsx

Change table colorscheme to from green to gray.
Before:
After:

Change table colorscheme to gray

---

frontend/beCompliant/src/components/MobileTableView.tsx
frontend/beCompliant/src/components/answer/Answer.tsx
frontend/beCompliant/src/pages/Table.tsx

fix aktivitiet typo

---

backend/src/main/kotlin/no/bekk/plugins/Routing.kt

Add simple health endpoint

---

frontend/beCompliant/src/components/MobileFilter.tsx
frontend/beCompliant/src/components/answer/Answer.tsx
frontend/beCompliant/src/components/questionRow/QuestionRow.tsx
frontend/beCompliant/src/components/tableActions/TableFilter.tsx
frontend/beCompliant/src/components/tableActions/TableSorter.tsx

Went a bit overboard when fixing the keys last time 😄

Fix key duplicates and remove unnecessary keys

---

frontend/beCompliant/src/components/MobileTableView.tsx
frontend/beCompliant/src/components/answer/Answer.tsx
frontend/beCompliant/src/components/questionRow/QuestionRow.tsx
frontend/beCompliant/src/hooks/datafetcher.ts

Setter bakgrunnsfargen i Select-elementet basert på det valgte alternativet. Fargene kommer fra Airtable. Det som må fikses er at teksten burdes gjøres hvit hvis bakgrunnsfargen er for mørk. Skal se på det, men begynner med denne:

Change answer background color

---

frontend/beCompliant/src/components/tableStatistics/TableStatistics.tsx
frontend/beCompliant/src/hooks/answersFetcher.ts
frontend/beCompliant/src/hooks/datafetcher.ts
frontend/beCompliant/src/pages/Table.tsx

Statistikken baserer seg nå på dataen som faktisk vises på skjermen

Change statistics to only count filtered data

---

backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/resources/db/migration/V1.10__add_comment_table.sql
backend/src/main/resources/db/migration/V1.8__add_comment_column.sql
backend/src/main/resources/db/migration/V1.9__remove_comment_column.sql
frontend/beCompliant/src/components/answer/Answer.tsx
frontend/beCompliant/src/components/questionRow/QuestionRow.tsx
frontend/beCompliant/src/hooks/commentsFetcher.ts
frontend/beCompliant/src/pages/Table.tsx

A simple comment-functionality. Probably needs some design work
This PR also includes making a table for comments, fetching comments and combining them and new endpoints for posting and getting comments.

Add possibility to comment on answers/questions etc

---

frontend/beCompliant/package-lock.json
frontend/beCompliant/package.json
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/table/DataTableCell.tsx
frontend/beCompliant/src/components/table/DataTableHeader.tsx

Tanstack table: https://tanstack.com/table/latest/docs/framework/react/examples/basic
We discussed using tanstack table at lunch, there is a lot of complexx state handling and such for the table and if we could use the tanstack table we would get all of that logic for free out of the box along with other things like search, sorting, hide column etc. 
In this PR I have made the visual components/ building blocks that will be used for creating the table, and I have made them generic. 
None of the code is being used as of now but we can continue and build on this further, it is nicer to have a look at a smaller PR then a single huge one I think

Create first building blocks for using tanstack table

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/table/DataTableSearch.tsx
frontend/beCompliant/src/components/table/Question.tsx
frontend/beCompliant/src/hooks/useDebounce.ts
frontend/beCompliant/src/pages/TablePage.tsx

- Created search component
- Created debounce hook
- Use debounce hook on table search to minimize number of updates
- Add search component to table component
- Added prop for table component if search field should be shown
Not using kvib search component because it was faulty, instead created same behaviour using input directly

Add the search component for the new table

---

backend/Dockerfile
frontend/beCompliant/Dockerfile

Både frontend og backend feiler under oppstart på SKIP.
Tror feilen ligger i Dockerfilene. Tester ut med endringene gjort i denne PR'en.

Updated Dockerfiles

---

frontend/beCompliant/Dockerfile

Update frontend dockerfile

---

frontend/beCompliant/Dockerfile

Updated dockerfile

---

frontend/beCompliant/vite.config.cjs

Reverts kartverket/regelrett#96

Revert "Test"

---

frontend/beCompliant/tsconfig.node.json
frontend/beCompliant/vite.config.mjs

Make tsconfig like it was

---

frontend/beCompliant/src/components/answer/Answer.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/DataTable.tsx

Fixed:
1. Should be able to give blank answer (in case of misclick or similar)
2. Added React.Fragment with unique key to get rid of warning

Two small bug fixes

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/layout/Page.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/Comment.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/table/DataTableCell.tsx
frontend/beCompliant/src/components/table/DataTableHeader.tsx
frontend/beCompliant/src/components/table/DataTableSearch.tsx
frontend/beCompliant/src/components/table/TableStatistics.tsx
frontend/beCompliant/src/components/tableActions/TableActions.tsx
frontend/beCompliant/src/components/tableActions/TableFilter.tsx
frontend/beCompliant/src/hooks/useColumnVisibility.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/routes.tsx

Magnus har gjort lit design endringer i figma, 
https://www.figma.com/design/yjsvqDN9EZXuq3UmsH53uK/Kartverket-sikkerhetsaktiviteter---versjon-1?node-id=403-1202&m=dev
vi har parprogget og fått implementert mye av det her.

Design update tablepage

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/table/DataTableHeader.tsx
frontend/beCompliant/src/components/table/DataTableSearch.tsx
frontend/beCompliant/src/hooks/useColumnVisibility.ts
frontend/beCompliant/src/utils/fillmodeColumns.ts

We wanted a kind of "Fill mode" where the user gets fewer columns to worry about when answering, to make it nicer to answer.
Implement the solution using the states we had + some helper functions

Predefined filtering

---

backend/docs/data-model.md

We have created an internal data model, where we have tried to structure the data we operate with inside of the backend code that we supply to the frontend in a sensible way. This has resulted in us making a ton of decisions about what will be good choices for the future, and should therefore try to document how it is designed, and the reasoning behind it.
Made a first version of a document describing the data model, which argues for why we have done it the way we have. I have described the different objects involved in detail, by describing the fields and their uses. This is my first time trying to document in this way, so any feedback is greatly appreciated. I want to reiterate that this is a _first_ version, and I hope we'll have many updates in the future to improve it.

Internal model docs

---

backend/docs/code-structure.md

We have a backend application that is growing into an api that is supposed to provide data from different providers, and therefore needs a structure that makes it easier to understand how the application works, and how it should be shaped.
This is my pitch for an architecture document, explaining the different parts of the backend and their purpose. I realized as I wrote it that my sense of "decoupling" is largely inspired by the Spring Boot way of doing things. This isn't necessary in Ktor, but you should still find some structure that manages to separate concerns. So, this is just an idea, which the application isn't fully compliant with as we speak but have drifted towards as we have developed it the last couple of weeks.

Architecture docs

---

frontend/beCompliant/package-lock.json
frontend/beCompliant/package.json

Det ble oppdaget en kritisk SSRF sårbarhet i Axios, som kanskje eller kanskje ikke påvirket oss.
Oppgraderer til nyeste versjon som inkluderer en fiks for feilen

Upgrade Axios

---

frontend/beCompliant/README.md

We need documentation for how to get the frontend project up and running
And also how it works
Write the documentation

Updated documentation in frontend project repo

---

backend/README.md

update backend docs to include all new things added
For me it looks like the backend docs is already complete.
Added links to the documentation in the main backend documentation

Added links to rest of docs for backend

---

frontend/beCompliant/src/components/table/pagination/PaginationRelativeButtons.tsx
frontend/beCompliant/src/utils/fillmodeColumns.ts

Utfyllingsmodus was wrong after new name of aktivitets column
change the list of columns for the utfyllingsmodus

Changed the aktivitet column to sikkerhetskontroller

---

backend/README.md
backend/docs/build-and-deployment.md
frontend/beCompliant/README.md
frontend/beCompliant/docs/build-and-deployment.md

Vi trenger docs for deployemnt og workflow
Skapte backend og frontend docs for workflows

Added documentation for the workflows for both backend and frontend

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/layout/Page.tsx
frontend/beCompliant/src/components/protectedRoute/ProtectedRoute.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/Comment.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/table/DataTableCell.tsx
frontend/beCompliant/src/components/table/DataTableHeader.tsx
frontend/beCompliant/src/components/table/DataTableSearch.tsx
frontend/beCompliant/src/components/table/DeleteCommentModal.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/components/table/TableStatistics.tsx
frontend/beCompliant/src/components/table/pagination/PaginationActionButton.tsx
frontend/beCompliant/src/components/table/pagination/PaginationButtonContainer.tsx
frontend/beCompliant/src/components/table/pagination/PaginationRelativeButtons.tsx
frontend/beCompliant/src/components/tableActions/TableActions.tsx
frontend/beCompliant/src/components/tableActions/TableFilter.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/FrontPage.tsx

Changes to increase consistency in frontend code
Renamed Props, ex. TableProps -> Props
Changed to full naming, ex. px -> paddingX
Removed unnecessary wrapping, ex. color={'blue'} -> color='blue'
Removed unused imports

renamed props, changed to full names and removed object wrapping

---

.github/workflows/add-issue-to-project.yml

Added a workflow file for issues

---

.github/workflows/add-issue-to-project.yml

Added correct version for issue workflow

---

.github/workflows/add-issue-to-project.yml

Added a new access token

---

.github/workflows/add-issue-to-project.yml

Added default column to created issue

---

frontend/beCompliant/.env
frontend/beCompliant/.env.production
frontend/beCompliant/.gitignore

Remove env-files

---

frontend/beCompliant/.env.production

update production .env

---

backend/src/main/kotlin/no/bekk/routes/AuthenticationRouting.kt

Move /callback out of authenticate-block

---

.github/pull_request_template.md
README.md
backend/.gitignore
backend/README.md
backend/build.gradle.kts
backend/src/main/kotlin/no/bekk/plugins/Routing.kt

Når jeg  jobbet med Lars såg jeg at navnet på databasen er regelrett i dev/prod
bytte navn på databasen lokalt
Solves #176

Changed the name of the db to regelrett as that is the name of the db when it gets deployed for consistency

---

frontend/beCompliant/src/components/Table.tsx

All columns sorted on the ID field since the accessor function returned an entire row object to sort on.
Defined a custom sorting function that used the value field in the row object to sort on.
#194

Fix sorting columns and correct sorting direction

---

backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/table/TableCell.tsx

Legge til ny rad i databasen for å kunne ha historikk på svarene og kommentarene
Endret slik at raden i databasen ikke blir erstattet, men ny legges heller til
#149 
#150

inserts new row in the database for each new comment and answer

---

.github/workflows/build-deploy-backend.yml
.github/workflows/build-deploy-frontend.yml

Want to also deploy to prod.
This PR sets ut the necessary steps required to deploy to prod-environment on SKIP. I have set it up with the use of GitHub Enviroments. `prod`-environment requires a manual review by an admin to run.

Setting up deploy to prod for frontend and backend

---

frontend/beCompliant/src/components/Table.tsx

All data forsvant da man brukte søkefeltet
Lagt til global filtreringsfunksjon i tabell-komponenten for å spesifisere hvordan data skal filtreres når søkefeltet blir brukt
#190

fix filtering when using search field

---

frontend/beCompliant/src/utils/tablePageUtil.ts

"Svar" og "Status" er ikke et felt i question-objektet som matcher filter navn. 
Custom filter funksjoner som håndterer filtrering av Status og Svar. Antar at dette bør gjøres på en litt mindre hardkodet måte, så tar gjerne i mot forslag til forbedring.
#191

fix filter on status and answer type

---

backend/README.md

When we fixed the authentication, the setup for local postgres has changed
Changed the readme to include the new way of doing it

Changed the documentation for local postgres setup

---

.github/workflows/build-deploy-frontend.yml
.gitignore
backend/Dockerfile
frontend/beCompliant/.env
frontend/beCompliant/.env.dev
frontend/beCompliant/.env.prod
frontend/beCompliant/.gitignore
frontend/beCompliant/Dockerfile
frontend/beCompliant/package.json

Adding separate builds for dev/prod

---

.github/workflows/build-deploy-backend.yml
.github/workflows/build-deploy-frontend.yml

The possibility of trigger a deploy of a chosen commit to environment of his/hers choice has not been working due to wrong syntax when reading out the inputs.
This PR will hopefully fix this.

Fixing manual trigger

---

.github/workflows/build-deploy-frontend.yml

Såg denne feilen når jeg gikk gjenonm workflowen, etter endringer av build joben gjetter jeg at pharos vil sjekke på prod builden
Endret til riktig job sin output

Add correct build output to the pharos step

---

backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/AuthenticationRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/kotlin/no/bekk/routes/TableRouting.kt
backend/src/main/kotlin/no/bekk/util/Logging.kt

No current feedback info about how the webserver behaves.
Added logging to provide useful information
#163

Logging webserver endpoints

---

.github/workflows/build-deploy-backend.yml
backend/Dockerfile
backend/build.gradle.kts

Suspecting that ./gradlew build does not include db migrations.
Therefore opting for ./gradlew buildFatJar.

Trying to fix db migrations on SKIP

---

backend/src/main/kotlin/no/bekk/authentication/Authentication.kt

Man blir logget ut etter 15min som er for kort tid
Endre til at man blir logget ut etter 3 timer i stedet
#223

Increased time from 15 to 180 minutes before you get logged out

---

frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/Comment.tsx
frontend/beCompliant/src/components/table/DeleteCommentModal.tsx
frontend/beCompliant/src/hooks/useDeleteComment.ts
frontend/beCompliant/src/hooks/useFetchTable.ts
frontend/beCompliant/src/hooks/useSubmitAnswers.ts
frontend/beCompliant/src/hooks/useSubmitComment.ts
frontend/beCompliant/src/pages/ActivityPage.tsx

På grunn av at tabelldataene ikke ble refetchet, var nye kommentarer i en ustabil tilstand, ref #224
Det er fortsatt ikke perfekt, men det er bedre med denne endringen. Nå refetcher vi tabelldataene i bakgrunnen når man gjør en kommentarhandling. Nye endringer vil fortsatt være litt ustabile, men det er heldigvis bare noen sekunder istedetfor til man laster inn siden på nytt.
Resolves #224

Fix comments behaving funky

---

settings.gradle.kts

changed the name of the rootProject in gradle to match new regelrett name

---

frontend/beCompliant/src/components/table/pagination/PaginationButtonContainer.tsx

Når man går inn på sitt team blir man automatisk scrollet ned på siden som er rar oppførsel
La til en sjekk på useEffecten til pagination. Endringen av sidene fungerer fortsatt likt, men siden scrolles ikke automatisk ned når man går inn på siden.
#255

The position of the view is at the top when opening the page

---

backend/src/main/kotlin/no/bekk/routes/AuthenticationRouting.kt
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/components/protectedRoute/ProtectedRoute.tsx
frontend/beCompliant/src/hooks/useLogOut.ts

Ingen måte å logge ut av applikasjonen på uten å manuelt slette cookien fra browser.
La til en logg ut knapp og et /logout endepunkt som sletter cookien fra usersession.
#159

added logout functionality

---

frontend/beCompliant/src/components/table/AnswerCell.tsx

Make background colour white instead of transparent on select

---

frontend/beCompliant/src/App.tsx
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/api/types.ts
frontend/beCompliant/src/hooks/useIsAuthenticated.ts

Det var en error i consolen at det returneres undefined fra "isLoggedIn" query key
Add return value for hook.
Also clean up the code a little bit
Resolves #276

Fix error message isLogged query key returning undefined

---

backend/src/main/kotlin/no/bekk/domain/AirtableResponseMapper.kt
backend/src/main/kotlin/no/bekk/model/internal/Question.kt
backend/src/main/kotlin/no/bekk/routes/TableRouting.kt
backend/src/main/kotlin/no/bekk/services/AirTableService.kt
backend/src/main/kotlin/no/bekk/services/TableService.kt
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/api/types.ts
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/hooks/useFetchQuestion.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx
frontend/beCompliant/src/routes.tsx

added endpoint to fetch single record from airtable

---

frontend/beCompliant/src/components/CSVDownload.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/tableActions/TableActions.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

vi vil kunne laste ned en csv fil av det som vises i tabellen som kan sendes videre
skaper en string som representerer en csv fil, lager en link for denne stringen og legger til en knapp for nedlasting.
Har ikke tenkt veldig mye på plassering og design her uten bare funktionalitet
Resolves #238

CSV download

---

backend/src/main/kotlin/no/bekk/database/DatabaseAnswer.kt
backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
frontend/beCompliant/src/api/types.ts
frontend/beCompliant/src/components/CSVDownload.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/components/table/TableStatistics.tsx
frontend/beCompliant/src/hooks/useSubmitAnswers.ts
frontend/beCompliant/src/types/tableTypes.ts
frontend/beCompliant/src/utils/tablePageUtil.ts

Svar og answer var brukt om hverandre som kunne skape forvirring.
Endret navn på Svar til answer i typer.
#275

rename svar to answer

---

backend/src/main/kotlin/no/bekk/services/TableService.kt
frontend/beCompliant/src/components/Table.tsx

Made changes according to the new AirTable setup

made solution compatible with new airtable update

---

backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt
backend/src/main/kotlin/no/bekk/database/CommentRepository.kt
backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/hooks/useFetchAnswersForQuestion.ts

For å slippe å filtrere blant alle svarene til alle spørsmålene trengte vi en måte å hente ut svarene til et spesifikt spørsmål. Det er da til redigeringssiden.
La til et endepunkt som fetcher svarene til et spesifikt spørsmål
#264

add endpoint to fetch answers for specific question

---

backend/src/main/kotlin/no/bekk/database/CommentRepository.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/hooks/useFetchCommentsForQuestion.ts

For å slippe å hente ut alle kommentarene og deretter filtrere for å få de som er til et spesifikt spørsmål. Vil brukes i redigeringssiden.
La til et endepunkt
#263

add endpoint to fetch comments for specific question

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt
backend/src/main/kotlin/no/bekk/database/CommentRepository.kt
backend/src/main/kotlin/no/bekk/database/DatabaseAnswer.kt
backend/src/main/kotlin/no/bekk/database/DatabaseComment.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/kotlin/no/bekk/util/RecordIDMapper.kt
backend/src/main/resources/db/migration/V2__add_record_id.sql
backend/src/main/resources/db/migration/V3__add_answer_type_and_unit.sql
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/components/ErrorState.tsx
frontend/beCompliant/src/components/LoadingState.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/hooks/useFetchAnswersForQuestion.ts
frontend/beCompliant/src/hooks/useFetchCommentsForQuestion.ts
frontend/beCompliant/src/hooks/useSubmitAnswers.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx

Ble kluss når kommentarene og svarene til et spørsmål ble hentet ut med questionID i stedet for recordID
La til recordId på answer og comment i databasen.
La også til answerType og answerUnit i answer tabellen i databasen for Andreas.
Implementerte RecordIDMapper som sjekker om det er noen tomme rader, og da evt. populerer de med data fra AirTable
Oppdaterte endepunktene for svar og kommentar til å nå bli kalt med recordId i stedet for questionId
Oppdaterte frontend der det trengtes

262 update database and endpoint

---

backend/src/main/kotlin/no/bekk/routes/TableRouting.kt
backend/src/main/kotlin/no/bekk/services/TableService.kt
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/hooks/useFetchColumns.ts

Trengte data til redigeringsiden som ikke lagres på question, men i metadata.
Implementerte et endepunkt som kun returnerer columns eller metadata fra airtable
#309

add new endpoint to fetch columns/metadata

---

frontend/beCompliant/src/components/questionPage/QuestionInfoBox.tsx

Vise mer informasjon om spørsmålet på spørsmålssiden
Implementerte infobox som vil bli tatt i bruk i QuestionPage
Resolves #267

implement info box for question page

---

frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx
frontend/beCompliant/src/components/questionPage/RadioAnswer.tsx
frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/hooks/useFetchAnswersForQuestion.ts
frontend/beCompliant/src/pages/QuestionPage.tsx

De første elementene på spørsmålssiden ligner nå på skissene
Tar hensyn til svartype - foreløpig tekst og select single
La til tilbakeknapp
#262 
https://github.com/user-attachments/assets/358d5ef9-8969-417f-b580-28069422da8b
https://github.com/user-attachments/assets/293674f3-36fb-4cf3-9b5d-20193858313a

262 fix design question page

---

frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionComment.tsx
frontend/beCompliant/src/components/questionPage/QuestionInfoBox.tsx
frontend/beCompliant/src/components/questionPage/RadioAnswer.tsx
frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
frontend/beCompliant/src/components/table/UnsavedChangesModal.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx

- La til komponenter i question page
- Prøvde å gjøre siden litt mer responsiv
- La til en modal som dukker opp hvis man har gjort endringer man ikke har lagret, og prøver å gå tilbake.
Resolves #334

add components in question page and modal for unsaved changes

---

backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt
backend/src/main/kotlin/no/bekk/database/CommentRepository.kt

Brukere får ikke alltid se riktig svar på tabellen da feil svar kan bli hentet ut.
La til sortering når svar eller kommentarer hentes ut fra databasen
Resolves #337

add sorting when fetching from database

---

backend/build.gradle.kts
backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt
backend/src/main/resources/application.yaml

Unsecure application
Added csp header to http response with 'default-src'. Various resources such as scripts, styles, images, fonts, etc are only allowed to be loaded from the website domain and server domain.
(!!! From my research CSP headers are not directly effective against SSRF attacks. Maybe create a new issue if SSRF vulnerability is a major concern)
#162

Add csp header

---

frontend/beCompliant/src/components/answers/PercentAnswer.tsx
frontend/beCompliant/src/components/answers/TimeAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionComment.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx

Nå er det mulig å endre svar med prosent og tid på spørsmålssiden
Resolves #340

add answer for percent and time to question page

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx
frontend/beCompliant/src/routes.tsx

Spørsmålssiden ble ikke lastet inn for SLA-skjema da tableId var hardkodet i frontend
Endret til å hente ut riktig tableId
Resolves #344

fix tableId in question page

---

backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt
backend/src/main/kotlin/no/bekk/database/CommentRepository.kt
backend/src/main/kotlin/no/bekk/database/DatabaseAnswer.kt
backend/src/main/kotlin/no/bekk/database/DatabaseComment.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/resources/db/migration/V5__add_context_id.sql
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionComment.tsx
frontend/beCompliant/src/components/questionPage/RadioAnswer.tsx
frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/Comment.tsx
frontend/beCompliant/src/hooks/useFetchAnswers.ts
frontend/beCompliant/src/hooks/useFetchComments.ts
frontend/beCompliant/src/hooks/useSubmitAnswers.ts
frontend/beCompliant/src/hooks/useSubmitComment.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx
frontend/beCompliant/src/routes.tsx

add functionality for context

---

frontend/beCompliant/src/components/tableActions/TablePicker.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

remove filters when switching table

---

frontend/beCompliant/src/components/questionPage/QuestionHistory.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/FrontPage.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx
frontend/beCompliant/src/routes.tsx

add tableId to url to store table state

---

backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/kotlin/no/bekk/database/DatabaseContext.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
backend/src/main/resources/db/migration/V7__add_context_table.sql

connect context to team

---

frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/hooks/useSubmitContext.ts
frontend/beCompliant/src/pages/CreateContextPage.tsx
frontend/beCompliant/src/routes.tsx

page for creating contexts

---

frontend/beCompliant/src/components/answers/TimeAnswer.tsx

added useeffect hook to set default time unit value

---

backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/kotlin/no/bekk/database/DatabaseContext.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
backend/src/main/kotlin/no/bekk/util/RemoveTeamAndFunctionHelper.kt
backend/src/main/resources/db/migration/V8__add_table_id_to_context.sql
frontend/beCompliant/src/hooks/useFetchCommentsForQuestion.ts
frontend/beCompliant/src/hooks/useSubmitContext.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/CreateContextPage.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx

Change context to contain table

---

backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt

Bugfix: added missing context endpoint

---

frontend/beCompliant/src/api/apiConfig.ts

API configen hadde at comment pathen var til /answer
#387

Bugfix: Lagre kommentar feiler

---

frontend/beCompliant/src/hooks/useFetchTeamContexts.ts
frontend/beCompliant/src/pages/FrontPage.tsx

added correct tableId to frontpage context links

---

frontend/beCompliant/.env.local_docker
frontend/beCompliant/nginx/nginx.conf
frontend/beCompliant/nginx/nginx.conf.template
frontend/beCompliant/package.json

Make nginx server run on SKIP

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/util/RemoveUnknownActorHelper.kt

remove unknown actor helper

---

frontend/beCompliant/src/components/answers/PercentAnswer.tsx

increase the amount of decimals to 4 for percent answers

---

frontend/beCompliant/src/pages/CreateContextPage.tsx

use search-params on create context page

---

.github/workflows/build-deploy-frontend.yml

bruke internal backend address for nginx redirect

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/hooks/useColumnVisibility.ts
frontend/beCompliant/src/utils/fillmodeColumns.ts

Fix fill mode

---

frontend/beCompliant/src/pages/CreateContextPage.tsx

fix redirect back to regelrett

---

frontend/beCompliant/src/hooks/useSubmitComment.ts

invalidate comments after submit

---

frontend/beCompliant/src/pages/ActivityPage.tsx

add filter query parameter

---

frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/questionPage/RadioAnswer.tsx
frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/hooks/useFetchAnswers.ts
frontend/beCompliant/src/hooks/useFetchAnswersForQuestion.ts
frontend/beCompliant/src/hooks/useSubmitAnswers.ts
frontend/beCompliant/src/pages/QuestionPage.tsx

fix invalidation of answer queries

---

backend/Dockerfile

fix-timezone-bug

---

frontend/beCompliant/src/pages/CreateContextPage.tsx

rename tabell og kontekst

---

frontend/beCompliant/src/components/questionPage/QuestionHistory.tsx

move questionhistorystep to own comp

---

frontend/beCompliant/.env.dev
frontend/beCompliant/.env.prod

Entra configs for SKIP

---

frontend/beCompliant/src/components/table/DataTable.tsx

fix toggling of utfyllingsmodus

---

frontend/beCompliant/src/components/Table.tsx

Sorter svar etter sist oppdatert

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/questionPage/QuestionInfoBox.tsx

Fjerne hardkodet søk, og infoboks på detaljside

---

frontend/beCompliant/src/pages/ActivityPage.tsx

add schema name to the heading in activity page

---

frontend/beCompliant/src/components/answers/PercentAnswer.tsx
frontend/beCompliant/src/components/answers/SingleSelectAnswer.tsx
frontend/beCompliant/src/components/answers/TextAnswer.tsx
frontend/beCompliant/src/components/answers/TimeAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx

remove button and save answers on blur

---

backend/src/main/kotlin/no/bekk/services/TableService.kt
frontend/beCompliant/src/components/Table.tsx

Reset pagination på søk og filter

---

frontend/beCompliant/src/components/tableActions/TableActions.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

Filtering answers only possible if all records have type single-select

---

frontend/beCompliant/src/components/table/DataTable.tsx

endre utfyllingsmodus til detaljert visning

---

backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/resources/db/migration/V11__replace_context_constraint.sql

replace context db constraint

---

frontend/beCompliant/src/components/answers/PercentAnswer.tsx
frontend/beCompliant/src/components/answers/TextAnswer.tsx
frontend/beCompliant/src/components/answers/TimeAnswer.tsx

only save answers if answer has changed

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/tableActions/TableActions.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

fix table reset on answer

---

frontend/beCompliant/src/components/RedirectBackButton.tsx
frontend/beCompliant/src/components/tableActions/TableActions.tsx

make return button and filters sticky

---

frontend/beCompliant/src/components/tableActions/TableActions.tsx

Ble et mellomrom mellom toppen og sticky filter-header når "tilbake"-urlen ikke eksisterer. Typ når man ikke kommer fra funkreg, men går direkte inn på en tabell fra regelrett.
Resolves #475

fix top when no back url

---

frontend/beCompliant/src/components/table/TableStatistics.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

skeleton loading activity page

---

frontend/beCompliant/src/hooks/useDeleteComment.ts
frontend/beCompliant/src/hooks/useSubmitAnswers.ts
frontend/beCompliant/src/hooks/useSubmitComment.ts

remove success toast

---

backend/src/main/kotlin/no/bekk/model/airtable/AirtableMapping.kt
backend/src/main/kotlin/no/bekk/model/internal/Answer.kt
frontend/beCompliant/src/api/types.ts
frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx

add checkbox answer type

---

frontend/beCompliant/src/components/Table.tsx

save sorting state to localStorage

---

.github/workflows/build-deploy-backend-gcp.yml
backend/build.gradle.kts
backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/kotlin/no/bekk/providers/AirTableProvider.kt
backend/src/main/kotlin/no/bekk/providers/TableProvider.kt
backend/src/main/kotlin/no/bekk/providers/YamlProvider.kt
backend/src/main/kotlin/no/bekk/providers/clients/AirTableClient.kt
backend/src/main/kotlin/no/bekk/routes/AirTableWebhookRouting.kt
backend/src/main/kotlin/no/bekk/services/TableService.kt
backend/src/main/resources/application-gcp.yaml
backend/src/main/resources/application.yaml

Airtable webhook

---

frontend/beCompliant/src/components/answers/TimeAnswer.tsx

Endre svar-enhet lagerer svaret

---

frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx
frontend/beCompliant/src/components/answers/PercentAnswer.tsx
frontend/beCompliant/src/components/answers/SingleSelectAnswer.tsx
frontend/beCompliant/src/components/answers/TextAnswer.tsx
frontend/beCompliant/src/components/answers/TimeAnswer.tsx
frontend/beCompliant/src/components/table/Comment.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/components/table/TableCell.tsx

Til nå har id vært link til spørsmålssiden, men dersom man skjuler kolonnen mister man mulighet til å komme seg til spørsmålssiden.
- Fjernet at id er link
- La til at når man holder over en rad så får den en border og hele raden blir klikkbar
- La til stopPropagation på svar og kommentar komponentene slik at man ikke blir navigated til spørsmålssiden når man svarer eller kommenterer
Gjerne klikk dere litt rundt for å dobbeltsjekke at alt funker som det skal
Resolves #490

navigate to question page from row

---

frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx
frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx

Gjøre teksten til checkbox konfigurerbar, den som kommer opp når boksen er checked eller unchecked.
Henter teksten fra svar-kolonnen i Airtable. Samme som for SELECT_SINGLE.
Resolves #502

checkbox text based on choices

---

.github/workflows/build-deploy-backend-gcp.yml

Forrige webhooks sluttet å funkgere siden de ikke ble håndtert riktig på GCP. Har laget nye webhooks

created new webhooks for gcp

---

frontend/beCompliant/src/pages/FrontPage.tsx

Endre knappen som sletter kontekster til rød søppelbøtte uten tekst
Resolves #520

change delete context button to red

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx
frontend/beCompliant/src/components/answers/PercentAnswer.tsx
frontend/beCompliant/src/components/answers/SingleSelectAnswer.tsx
frontend/beCompliant/src/components/answers/TextAnswer.tsx
frontend/beCompliant/src/components/answers/TimeAnswer.tsx
frontend/beCompliant/src/components/table/Comment.tsx
frontend/beCompliant/src/components/table/DataTable.tsx

Klikkbare rader er idiotisk
La til en rad foran med ikon og tekst i stedet. Var det beste jeg klarte å komme opp med, men bare å komme med forslag
Resolves #527

replace row onclick

---

frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx
frontend/beCompliant/src/hooks/useFetchAllContexts.ts
frontend/beCompliant/src/pages/CreateContextPage.tsx
frontend/beCompliant/src/pages/LockedCreateContextPage.tsx
frontend/beCompliant/src/pages/UnlockedCreateContextPage.tsx

Når en oppretter skjema er det nå mulig å kopiere svar fra eksisterende skjemaer fra **andre** teams enn ditt eget. Så lenge du har tilgang til teamene.
Gjorde også litt refactoring underveis som kanskje gjør PRen litt vanskeligere å lese 😅 
#477

copy answers from any team

---

backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
frontend/beCompliant/src/api/apiConfig.ts
frontend/beCompliant/src/components/table/SettingsModal.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

Lagt til mulighet for å endre hvilket team en skjemautfylling hører til.
#516

Change team of context

---

frontend/beCompliant/src/components/table/TableCell.tsx

Teksten kan knekke rart på noen rader
Økte max width på tekst-kolonner
Resolves #553

increase max width on text columns

---

frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/utils/fillmodeColumns.ts

"se mer" kolonnen vises ikke når man skrur av detaljert visning
La inn riktige kolonner i fillmodeColumns
Resolves #552

552 show more column detailed view

---

frontend/beCompliant/src/components/table/Comment.tsx

Hvis man har linjeskift i kommentaren skal denne vises.
Endret whitespace til "pre-wrap" på text-komponenten
Resolves #534

show new line in comment

---

backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt

removed comment csv

---

frontend/beCompliant/src/components/Table.tsx

Fjernet "se mer" tekst og la på tooltip istedenfor
#563

added tooltip and removed text

---

frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/table/TableCell.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

Ble mye whitespace på større skjermer - spesielt rundt spørsmålsteksten når "detaljert visning" var skrudd av. Endret til at tabellen ikke stretcher over hele skjermen hvis det ikke trengs og heller sentreres på midten.
--> 
#564

Fix whitespace questions

---

.github/workflows/build-deploy-backend-gcp.yml
backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt
backend/src/main/resources/application.yaml

Fjernet unødvendig frisk host konfigurasjon

remove frisk config

---

backend/src/main/kotlin/no/bekk/routes/TableRouting.kt

added back tables endpoint

---

backend/src/main/kotlin/no/bekk/routes/TableRouting.kt

staging -> main

---

frontend/beCompliant/src/components/table/LastUpdated.tsx

Ikonene var unødvendig store
endret på størrelsen
Resolves #583

smaller refresh answer and warning icon

---

backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
frontend/beCompliant/src/hooks/useFetchContext.ts
frontend/beCompliant/src/pages/ActivityPage.tsx

correct error message schema page

---

frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx
frontend/beCompliant/src/components/answers/PercentAnswer.tsx
frontend/beCompliant/src/components/answers/SingleSelectAnswer.tsx
frontend/beCompliant/src/components/answers/TextAnswer.tsx
frontend/beCompliant/src/components/answers/TimeAnswer.tsx
frontend/beCompliant/src/components/table/AnswerCell.tsx
frontend/beCompliant/src/components/table/TableCell.tsx

disable inputs on mutations

---

.security/risc/risc-wWyRD.risc.yaml

Jørn Ola Birkeland (Jorn.Birkeland@kartverket.no) has approved the risk scorecard. Merge the pull request to include the changes in the main branch.

Updated risk scorecard

---

.github/ISSUE_TEMPLATE/custom.md
README.md

Malinnsnieske patch 1

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/custom.md
.github/pull_request_template.md

Jeg heter gyda patch 1

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/custom.md
.github/pull_request_template.md
README.md
frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/table/DataTable.tsx
frontend/beCompliant/src/hooks/useColumnVisibility.ts

staging-> main

---

backend/build.gradle.kts
backend/gradle.properties

Fikset sårbarheter ved å oppgradere Json-smart og log.

631 fix sårbarheter

---

.github/ISSUE_TEMPLATE/custom.md

Oppdatere oppgavemalen etter prosesskartleggingen
**Løsning**
🆕 Endring:
Brukerhistorie -> problembeskrivelse
Fjernet løsningsbeskrivelse
**🧪 Testing**

Oppdaterte oppgavemal

---

.gitignore
README.md
backend/build.gradle.kts

fix: Lagt til flyway plugin så man kan gjøre oppsettet slik det er beskrevet i readme
Forenkle førstegangsoppsett for de som ikke bruker IntelliJ
**Løsning**
Legge til flyway sin gradle plugin, så den kan anvendes på den måten som allerede var beskrevet i readme.

Fix: gradle + flyway

---

frontend/beCompliant/package-lock.json
frontend/beCompliant/package.json

Vi i Team SKVIS har sårbarhetsarbeid på agendaen, og tar derfor en runde gjennom alle verktøyene 🤝  Dependabot rapporterer om en kritisk sårbarhet i vitest < 2.1.9. Alert ligger [her](https://github.com/kartverket/regelrett/security/dependabot/20).
**Løsning**
Oppdaterer vitest til versjon 2.1.9.
**🧪 Testing**
Det viktigeste er å sjekke at all funksjonalitet fungerer som det skal.
✨ Hopefully improved …

Attempt to fix critical vulnerability

---

frontend/beCompliant/Dockerfile

🥅 Mål med PRen: Faktisk fikse libxml2
**Løsning**
**🧪 Testing**

Upgrade libxml2 to fix vulnerabilities v2

---

frontend/beCompliant/Dockerfile

upgrade libxslt

---

frontend/beCompliant/Dockerfile

upgrade libexpat

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt
backend/src/main/kotlin/no/bekk/domain/MicrosoftGraphGroupsResponse.kt
backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt
backend/src/main/resources/application.yaml
frontend/beCompliant/Dockerfile
frontend/beCompliant/package-lock.json
frontend/beCompliant/package.json
frontend/beCompliant/src/App.tsx
frontend/beCompliant/src/components/Table.tsx
frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx
frontend/beCompliant/src/components/protectedRoute/ProtectedRoute.tsx
frontend/beCompliant/src/components/table/SettingsModal.tsx
frontend/beCompliant/src/hooks/useStoredRedirect.ts
frontend/beCompliant/src/hooks/useUser.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/CreateContextPage.tsx
frontend/beCompliant/src/pages/FrontPage.tsx
frontend/beCompliant/src/pages/LockedCreateContextPage.tsx
frontend/beCompliant/src/pages/QuestionPage.tsx
frontend/beCompliant/src/pages/UnlockedCreateContextPage.tsx
frontend/beCompliant/src/routes.tsx

Staging->main

---

.github/workflows/build-deploy-backend-gcp.yml

set cors env variable gcp

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/kotlin/no/bekk/routes/AirTableWebhookRouting.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
backend/src/main/kotlin/no/bekk/routes/FormRouting.kt
backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt
backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt
backend/src/main/kotlin/no/bekk/services/FormService.kt
backend/src/main/kotlin/no/bekk/services/MicrosoftService.kt
backend/src/main/kotlin/no/bekk/util/RefreshWebhookBackgroundTask.kt

refaktorisere formservice og microsoftService til klasser for å endre til injection pattern fra singletons. Gjør det enklere å teste og slipper kluss i module()
**Løsning**
🆕 Endring: 
Endre fra objects til klasser. Resten av endringene er injections av servicene der de er brukt
**🧪 Testing**
Resolves #682

682 refactor formservice and microsoftservice

---

backend/build.gradle.kts
backend/src/main/kotlin/no/bekk/Application.kt
backend/src/test/kotlin/no/bekk/ApplicationTest.kt
backend/src/test/resources/application.yaml

Legge til et par generelle tester for autentisering og cors
**Løsning**
🆕 Endring: 
La til tester
**🧪 Testing**
Resolves #688

688 legge til tester for autentisering og cors

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt
backend/src/main/kotlin/no/bekk/configuration/JDBCDatabase.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/kotlin/no/bekk/providers/clients/AirTableClient.kt
backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt
backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt
backend/src/main/kotlin/no/bekk/services/FormService.kt
backend/src/main/kotlin/no/bekk/services/MicrosoftService.kt
backend/src/test/kotlin/no/bekk/ApplicationTest.kt

Refaktorerte AppConfig for at den blir mer leselig og oppdaterte steder der hele configen ikke trenger å sendes. F.eks. i FormService så holdt det med kun FormConfig
**Løsning**
**🧪 Testing**
Resolves #696

696 refaktorere appconfig

---

backend/src/main/kotlin/no/bekk/services/MicrosoftService.kt

Legge til logging for å finne ut hvorfor kallet feiler
**Løsning**
**🧪 Testing**

add logging for debugging

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt
backend/src/main/kotlin/no/bekk/database/CommentRepository.kt
backend/src/main/kotlin/no/bekk/database/ContextRepository.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
backend/src/main/kotlin/no/bekk/services/FormService.kt
backend/src/test/kotlin/no/bekk/ApplicationTest.kt

Refaktorere resten fra object til klasser
**Løsning**
**🧪 Testing**
Resolves #698

698 refaktorere repository filene fra object til klasser

---

.github/workflows/codeql.yml

Legg til CodeQL for scanning av kjente sårbarheter i kode
**Løsning**
🆕 Endring: 
La til en action som kjøres ved hver pull request, hver gang main oppdateres og 05:16 hver tirsdag. CodeQL scanner etter kjente mønstre som kan inneholde sårbarheter
**🧪 Testing**

add codeQL scanning

---

backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/authentication/AuthService.kt
backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
backend/src/main/kotlin/no/bekk/di/Dependencies.kt
backend/src/main/kotlin/no/bekk/di/RootComposer.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt
backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt
backend/src/main/kotlin/no/bekk/services/AuthService.kt
backend/src/main/kotlin/no/bekk/services/MicrosoftService.kt
backend/src/test/kotlin/no/bekk/ApplicationTest.kt
backend/src/test/kotlin/no/bekk/MockAuthService.kt

🥅 Mål med PRen: 
Enklere testing av koden, og løsere kobling mellom de forskjellige kodebitene.
🆕 Endring: I dag må en bruke et bibliotek for å mocke ut kall til autentiseringsbiten av koden ved diverse tester. Nå holder det med en enkel implementasjon av et interface. Dermed får vi løsere kobling mellom komponentene, og en enklere vei for debugging av tester.
- Flyttet funksjonene fra Authentication til AuthService
- La til interface i MicrosoftService
- Resten er i stor grad oppdateringer som følge av flytting.
**🧪 Testing**
Resolves #707

Collect auth-related functions in a class

---

backend/build.gradle.kts
backend/src/test/kotlin/no/bekk/MockDatabase.kt
backend/src/test/kotlin/no/bekk/MockFormService.kt
backend/src/test/kotlin/no/bekk/MockMicrosoftService.kt
backend/src/test/kotlin/no/bekk/TestDatabase.kt
backend/src/test/kotlin/no/bekk/TestUtils.kt
backend/src/test/kotlin/no/bekk/integrationTests/AnswerIntegrationTest.kt
backend/src/test/kotlin/no/bekk/integrationTests/CommentIntegrationTest.kt
backend/src/test/kotlin/no/bekk/integrationTests/ContextIntegrationTest.kt

🥅 Mål med PRen: *
Legge til noen integrasjonstester som dekker flere lag av applikasjonen
**Løsning**
🆕 Endring:
La til noen integrasjonstester
**🧪 Testing**
Resolves #704

Add integration tests

---

backend/src/test/kotlin/no/bekk/database/AnswerRepositoryTest.kt
backend/src/test/kotlin/no/bekk/database/CommentRepositoryTest.kt
backend/src/test/kotlin/no/bekk/database/ContextRepositoryTest.kt
backend/src/test/kotlin/no/bekk/routes/AnswerRoutingTest.kt
backend/src/test/kotlin/no/bekk/routes/CommentRoutingTest.kt
backend/src/test/kotlin/no/bekk/routes/ContextRoutingTest.kt
backend/src/test/kotlin/no/bekk/routes/MockAnswerRepository.kt
backend/src/test/kotlin/no/bekk/routes/MockCommentRepository.kt
backend/src/test/kotlin/no/bekk/routes/MockContextRepository.kt

Legge til unit tester
**Løsning**
🆕 Endring: 
La til tester
**🧪 Testing**
Resolves #611

Add unit tests

---

frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx
frontend/beCompliant/src/hooks/useStoredRedirect.ts
frontend/beCompliant/src/pages/ActivityPage.tsx
frontend/beCompliant/src/pages/CreateContextPage.tsx
frontend/beCompliant/src/routes.tsx

🆕 Endring: 
Det var flere useEffects som kalte på setSearchParams. 
setSearchParams medfører navigasjon. Har satt replace = true i navigation options på alle kall, og fikset useEffects som medførte render loops.
Resolves #660

660 for å gå tilbake må man klikke to ganger

---

frontend/beCompliant/package-lock.json
frontend/beCompliant/src/components/table/SettingsModal.tsx
frontend/beCompliant/src/pages/ActivityPage.tsx

Når man kopierer skjemautfylling (i innstillinger) så kommer det ingen bekreftelse på at det var suksessfult og siden blir heller ikke oppdatert.
**Løsning**
Gir toast på suksess og feil, og refresher tabellen. 
**🧪 Testing**

Legg til bekreftelse på kopiert skjema og refersh tabeller

---

backend/Dockerfile
frontend/beCompliant/Dockerfile

Fikse pharos feilmeldinger med dockerfilene
**Løsning**
🆕 Endring: 
Usikker på om det ble riktig i frontend dockerfilen, men prøver
**🧪 Testing**

fix pharos alerts

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml

add build to deploy

---

.github/workflows/deploy-frontend.yml

set image url correctly

---

frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx
frontend/beCompliant/src/pages/CreateContextPage.tsx

Fikse litt styling på /ny siden
**Løsning**
🆕 Endring: 
- Satt på fontWeight=bold på overskriftene 
- Fikset lik bakgrunnsfarge og radiusBorder på feltene
- Fikk ikke til å endre borderColor så de ble like:((
Før:
Etter:
**🧪 Testing**
Resolves #734

fix bgcolor and fontweight

---

backend/build.gradle.kts
backend/gradle.properties
backend/src/main/kotlin/no/bekk/Application.kt
backend/src/main/kotlin/no/bekk/plugins/Routing.kt
backend/src/test/kotlin/no/bekk/ApplicationTest.kt

High security risk i forrige ktor-version ifølge pharos.
**Løsning**
Oppgradert ktor og kotlin og gjort nødvendige endringer i koden.
**🧪 Testing**

Upgrade ktor

---

frontend/beCompliant/src/components/DeleteContextModal.tsx
frontend/beCompliant/src/components/TeamContexts.tsx
frontend/beCompliant/src/components/protectedRoute/ProtectedRoute.tsx
frontend/beCompliant/src/components/table/TableStatistics.tsx
frontend/beCompliant/src/pages/FrontPage.tsx

Få dette til å se bedre ut:
**Løsning**
🆕 Endring: 
- Endret på fontene
- La til card rundt linkene
- La til progress circle i kortene
- La til en tekst under teamnavnet dersom det ikke har noen skjemautfyllinger
**🧪 Testing**
Resolves #663

663 forbedre oversiktside i regelrett

---

.github/workflows/deploy-backend.yml

extend cors for fly pr preview

---

backend/src/main/kotlin/no/bekk/database/DatabaseContext.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
frontend/beCompliant/src/hooks/useContext.ts
frontend/beCompliant/src/pages/createContextPage/CopyContextDropdown.tsx
frontend/beCompliant/src/pages/createContextPage/CreateContextPage.tsx

Kunne kopiere kommentarer i tillegg til svar på /ny siden
**Løsning**
🆕 Endring: 
La til at man kan velge å kopiere svar. Dukker bare opp hvis man velger å et skjema å kopiere svar fra. La til i post-endepunktet i backend
**🧪 Testing**
Resolves #774

copy comments when creating schema

---

backend/src/main/resources/application.yaml

Endrer env-variabelnavn for samsvar med hvordan det ser ut på skip.
Usikker på hvorfor det var anførselstegn rundt, gjerne si fra dersom det brekker noe.

Update env-variable name

---

frontend/beCompliant/package-lock.json
frontend/beCompliant/package.json

Bump react router til 7.5.2

---

backend/src/main/kotlin/no/bekk/plugins/RequestLogging.kt
backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt
backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt
backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt
backend/src/main/kotlin/no/bekk/routes/FormRouting.kt
backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt
backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt

Regelret har kun debug logging, og error /warn om det skjer noe feil. Umulig å søke i loggene nå om f eks slette kall om skjemaer har blitt kalt på eller ikke. endrer debug til info så de blir synlige i loggene.

Endre debug logging til info

---

backend/src/main/kotlin/no/bekk/configuration/ConfigBuilder.kt
conf/defaults.yaml

Add yaml schema

---

frontend/beCompliant/src/hooks/useAnswers.ts
frontend/beCompliant/src/pages/activityPage/table/AnswerCell.tsx

Når man sender inn svar, så vil ikke tabellen eller statistikken oppdatere seg med mindre man refresher siden.
**Løsning**
Refetcher alle answers istedetfor bare den som blir oppdatert.
**🧪 Testing**

rOppdater tabell når man sender inn svar

---

backend/src/main/kotlin/no/bekk/configuration/ConfigBuilder.kt
conf/defaults.yaml
conf/sample.yaml

Var litt rask på avtrekkeren, vi vil selfølgelig ikke ha testdata i prod 🥴

Ikke ta med testdata i prod

---

frontend/beCompliant/src/hooks/useAnswers.ts
frontend/beCompliant/src/pages/activityPage/table/AnswerCell.tsx
frontend/beCompliant/src/pages/activityPage/table/TableCell.tsx
frontend/beCompliant/src/pages/frontPage/TeamContexts.tsx
frontend/beCompliant/src/pages/questionPage/QuestionAnswer.tsx
frontend/beCompliant/src/pages/questionPage/QuestionHistory.tsx
frontend/beCompliant/src/pages/questionPage/RadioAnswer.tsx
frontend/beCompliant/src/pages/questionPage/TextAreaAnswer.tsx

Hvis man submitter et svar, så vil alle inputfeltene i skjemaet låse seg til nettverkskallet har resolvet. 
**Løsning**
Endrer slik at det er kun det relevante inputfeltet som låser seg. Legger også til disabled-state på alle inputfelt på question page, samt rydder litt i nettverkskallene.
Resolves #844

Kan ikke legge inn svar før nettverkskall resolver

---

frontend/beCompliant/src/pages/activityPage/table/TableCell.tsx
frontend/beCompliant/src/pages/questionPage/QuestionDetails.tsx
frontend/beCompliant/src/pages/questionPage/QuestionPage.tsx

Alle verdiene vises ikke hvis det er flere på detaljsiden, kun det første element. Sist endret viser også "0 sekunder siden" hvis den aldri har blitt endret.
**Løsning**
Viser alle verdiene på et felt, med riktig bakgrunnsfarge. Viser også Sist endret til å vise "Aldri" hvis den ikke har blitt endret før
Resolves #912 (Delvis ihvertfall)

912 kategori vises ikke riktig
