frontend/be-compliant/src/components/questionRow/QuestionRow.tsx, frontend/be-compliant/src/components/table/Table.tsx, frontend/be-compliant/src/hooks/datafetcher.ts
Previously we rendered only certain columns. For a more robust solution the columns and rows are rendered by iterating over the data and metadata. The only columns that are hardcoded, are the "system columns": Når, Status and Svar. Likely Svar should be defined by the data from Airtable instead of being hard coded. 
Before:
After:
=> Render all columns

frontend/be-compliant/src/components/answer/Answer.tsx
To give the user feedback about the status of their action after answering a question we added a toast for a successful and unsuccessful answer. 
Before:
After:
=> Add toast feedback for correct and incorrect answers

frontend/beCompliant/src/App.css, frontend/beCompliant/src/components/questionRow/QuestionRow.tsx, frontend/beCompliant/src/pages/Table.tsx
Fjerner statuskolonnen, men beholder Statusfilteret. Når man baker inn denne i Svar-filteret, så mister man sannsynligvis muligheten til å vise alle utfylte, uavhengig av svar. Tenker dette er et steg i riktig retning ihvertfall
=> Remove status column

frontend/beCompliant/src/components/MobileFilter.tsx, frontend/beCompliant/src/components/MobileTableView.tsx, frontend/beCompliant/src/components/answer/Answer.tsx, frontend/beCompliant/src/components/questionRow/QuestionRow.tsx, frontend/beCompliant/src/components/tableActions/TableActions.tsx, frontend/beCompliant/src/components/tableActions/TableFilter.tsx, frontend/beCompliant/src/pages/Table.tsx
When using index as the key, it may create problems. Example: An answer uses the index as key and you remove a row from the table. Since the index still exists, the answer will visually "jump" to the same index, which is now the "next" row (with the same index)
=> Make all keys unique, fix bug where answers would move when using a filtered table

frontend/beCompliant/src/components/MobileTableView.tsx, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/answer/Answer.tsx, frontend/beCompliant/src/components/questionRow/QuestionRow.tsx, frontend/beCompliant/src/components/tableActions/TableFilter.tsx, frontend/beCompliant/src/components/tableActions/TableSorter.tsx, frontend/beCompliant/src/components/tableStatistics/TableStatistics.tsx, frontend/beCompliant/src/hooks/answersFetcher.ts, frontend/beCompliant/src/hooks/datafetcher.ts, frontend/beCompliant/src/pages/TablePage.tsx, frontend/beCompliant/src/routes.tsx, frontend/beCompliant/src/utils/sorter.tsx
We want to create a more generic table component that can accept any set of columns. To achieve this we need tos separate the data handling from the data we want to display.
This isn't an end goal, but I decided to do it gradually to avoid making too many changes in one go. It's easier if we discuss step by step.
* Refactored the name of the `Table` file to be `TablePage`. It's a route, that does a lot of data fetching, manipulation and presentation, it is not a pure component.
* Added the state of fetching new answers to the `useAnswersFetcher`, instead of simply passing it through `Table` -> `QuestionRow` -> `Answer`. This way Table has no state except its data.
* Created a new Table component that accepts the data to display, the fields that make up the table, as well as the team and …
=> Add refetching to userAnswersFetcher hook and create new Table component

frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/DataTableHeader.tsx, frontend/beCompliant/src/components/table/Question.tsx
We want to be able to sort our table, and it not being tighly bound to the current amount of column.
* Added sorting of the column to the `DataColumnHeader` component. Allows you to sort ascending, descending and neither.
* Rewrite `TableComponent` to use `DataTable`, with generically defined column definitions. These definitions should probably be memoized in a hook, but one thing at a time.
* Created a `Question` component that _should_ be able to replace `QuestionRow` in the long run. This component looks at the data about the column to determine styling, instead of it having to be passed down as a part of the row data. The **only** missing feature here is to handle the `Answer` component, which is not incidentally the most complex. The biggest issue right now is that we actually can't …
=> Sort TanStack table

backend/build.gradle.kts, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/Comment.tsx, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/pages/TablePage.tsx
We have made a more generic table that uses the Tanstack library, but we haven't replaced the old one yet because it did not support the answer column.
In this solution, I've went for an index-based way of figuring out which column is the answer column (3). This means that we can't have multiple answers per question, and it can't be moved around. **But** we can change the name of the column without it breaking!
* Renamed the `Question` component to instead be named `TableCell` which is a more descriptive name as it represents a single cell in the table. Extended it to accept a new prop to it that informs the component if the cell is "answerable", resulting in rendering a new `AnswerCell` instead of a static view.
* Created a new `AnswerCell` component, that renders different ways to …
=> Datatable answer column

frontend/beCompliant/src/hooks/useLocalstorageState.ts, frontend/beCompliant/src/pages/TablePage.tsx
Nå kan man skjule kolonner som ikke er interessante, men de nullstiller seg når siden laster inn på nytt. Da må man skjule de samme kolonnene hver gang man bruker tjenesten.
Løsningen er å lagre tilstanden om skjulte kolonner i localstorage. Da blir de husket mellom hver session.
=> Store hidden column state in localstorage

frontend/beCompliant/.env, frontend/beCompliant/.env.production, frontend/beCompliant/.gitignore, frontend/beCompliant/src/main.tsx
The previous solution to inject the urls for the frontend and backend weren't working in production. Since the urls are not sensitive information they can be stored in .env files in the frontend folder.
Create an .env file for local development and a .env file for dev/production. The .env files contain the urls for the frontend and backend service. Vite prioritizes .env files with `MODE` higher than standard .env files. Furthermore, Vite only loads .env files with modes conditionally. When running `npm run dev` only the .env file is loaded and if `npm run build` both files are loaded, but **.env.production** is prioritized. You can read more about how Vite configures and handles environment variables here https://vitejs.dev/guide/env-and-mode
=> Create fronted env files for urls

backend/src/main/kotlin/no/bekk/plugins/Cors.kt
Allowed cors headers only allowed localhost:3000. This needs to be an env variable to allow frontend host injected in dev environment. 
Change hardcoded host to env variable.
=> Add env variable to allowed hosts in cors config

backend/src/main/kotlin/no/bekk/configuration/ConfigureDatabase.kt, backend/src/main/kotlin/no/bekk/plugins/Cors.kt, backend/src/main/kotlin/no/bekk/plugins/FlywayMigrate.kt, backend/src/main/resources/application.conf.template, compose.yaml
When running in SKIP the configuration files are not added since its has the template suffix. This caused a null point exception. Also, host was hardcoded which breaks docker compose.
Created a funciton that checks if environment variables or config variables exist. In SKIP we still won't have config values because the files is not added by dockerfile. But as long as there exists ENV variables the function will not throw an exception. The config file should maybe be added in the future or at least be consistent with environment variables.
=> Fix db config null handling

frontend/beCompliant/src/components/layout/Page.tsx, frontend/beCompliant/src/pages/FrontPage.tsx, frontend/beCompliant/src/routes.tsx
The landingpage with links to each team was left aligned in another pr. The content should be centered. The title should also be centered, but the text should be left aligned. The colour on the links should also be blue to follow the new theme. Lastly the page content should take up 100 viewport height with the gray background colour for a cohesive design
Mostly added some css styling to solve these issues. And added a new flexbox in the frontpage to center content and be able to left align title text
=> Center team selection

backend/src/main/kotlin/no/bekk/controllers/TableController.kt, backend/src/main/kotlin/no/bekk/database/DatabaseAnswer.kt, backend/src/main/kotlin/no/bekk/database/DatabaseComment.kt, backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt, backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt, backend/src/main/kotlin/no/bekk/plugins/Routing.kt, backend/src/main/kotlin/no/bekk/routes/AlleRouting.kt, backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt, backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt, backend/src/main/kotlin/no/bekk/routes/KontrollereRouting.kt, backend/src/main/kotlin/no/bekk/routes/MetodeverkRouting.kt, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/Comment.tsx
This PR became a combo of backend refactoring and frontend featuring. We wanted to sort all the routes into separate files, and also have the Comment field as its own column in the table.
* Made own files for all route domains except the basic health endpoint stuff. Not sure if all of the ones are necessary/useful but decided to not remove any in this PR, just refactor.
* Moved data classes used in serialization for specific routes to domain specific folders.
* Moved the comment data into its own column, and place it after the answer column if possible. Now it's possible to hide comments as any other column, and they'll always be visible if not. This solution is hard-coded and frankly not pretty, another good reason to use the abstraction layer previously introduced in the backend.
=> Sort routing and separate the comment into own column

backend/src/main/resources/logback.xml
We were logging a lot as we logged every trace
Change logging level to info, which hopefully will give more relevant logs, such as errors and warnings
=> Reduce logging

frontend/beCompliant/src/utils/tablePageUtil.ts
The "Når" or updated column in the table only updated when comments were submitted and not answers. We thought that the status of the answers is the most important and the updated value of the answer should dictate the value of the "Når"/updated column.
After some discussion in the team we landed on only showing the updated value of the answer is the most important. The old solution combined the data from the backend with comments and answers. Both of these data models have the updated field with individual values. When combining the data, since the comments were the last in the function the comment updated value would overwrite the answer updated value if it existed. For now a simple solution is to switch the logic such that the answer data will, if both are present, overwrite the …
=> Rearrange combine function such that answer overwrites comment when merging

backend/src/main/kotlin/no/bekk/controllers/TableController.kt, backend/src/main/kotlin/no/bekk/model/internal/Question.kt, backend/src/main/kotlin/no/bekk/routes/TableRouting.kt, frontend/beCompliant/src/api/apiConfig.ts, frontend/beCompliant/src/api/types.ts, frontend/beCompliant/src/hooks/useFetchTable.ts
We have created a new internal model in the backend that the data sources should be mapped to before it is served to the frontend. This way we have more control over the data the frontend receives, and are less tangled into Airtable specific rarities.
Now we want to fetch this data as a model in the frontend.
Refactored the backend a bit because we don't actually want the frontend to have any relationship with the datasources we are fetching from (such as Airtable), so I scrubbe the source away from the endpoint. Also, creating a semi-mapping between an internal schema id and the Airtable id, such that we know which service to use to fetch the data in case we have multiple data providers.
In the frontend I have created types for all the data that we get from the backend, these are mirrors …
=> Frontend internal model

backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt, backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/Comment.tsx, frontend/beCompliant/src/components/table/DeleteCommentModal.tsx, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/hooks/useDeleteComment.ts, frontend/beCompliant/src/hooks/useSubmitComment.ts
We want to improve the experience of using comments. Today it is just a text field that you can update. If you start to edit it you'll have to refresh to get the old state, and it is technically impossible to delete a comment.
Create different "modes" for the comment component:
* If the question has no comment it simply shows an add comment button. In read mode you can either choose to edit the comment, or delete it completely.
* When you choose to delete it you'll get a confirmation modal to make sure that you want to commit to it. I have added m
ethods to the backend to be able to delete comments now, and this will trigger it using it a new hook.
* In edit mode you can either submit the comment which will update the database, or you can discard the changes. This will result in the field …
=> Comment edit mode

frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/components/table/pagination/PaginationButtonContainer.tsx, frontend/beCompliant/src/components/table/pagination/PaginationRelativeButtons.tsx, frontend/beCompliant/src/types/tableTypes.ts
The text in the question column did not wrap anything despite being to wide. 
When you first render the page you the page is scrolled to the bottom which is not wanted behaviour.
Fixed issues mentioned above. Added whitespace to the text in the tablecell. Also removed the useState and useEffect hooks and instead run the scrolling when the button is clicked
=> Fixed question text wrapping/overflow + page scroll bug

backend/src/main/kotlin/no/bekk/authentication/Authentication.kt, backend/src/main/kotlin/no/bekk/plugins/Config.kt, backend/src/main/kotlin/no/bekk/plugins/Routing.kt, backend/src/main/kotlin/no/bekk/routes/AuthenticationRouting.kt
After implementing authentication with Entra Id it is not possible to develop locally without correctly authenticating with Entra ID. 
To solve this there should optimally be a Entra ID development area where we could authenticate mocked users to with a client id and client secret. Due to time restrictions and uncertainty of how to create an "optimal" solution as described above, a simple fix is to abstract away authentication and group authorization for local development
Add a system variable as such `"ENVIRONMENT" "development"`
=> Remove authentication and mock groups for local development

backend/src/main/kotlin/no/bekk/routes/QuestionRouting.kt, backend/src/main/kotlin/no/bekk/routes/TableRouting.kt, backend/src/main/kotlin/no/bekk/services/QuestionService.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt
Ktor uses the naming convention "Routes" not "Controller". The files in the controller repo contains business logic that should be under services.
Moved the controller files to services directory and renamed them to have a Service suffix.
=> refactored controllers to service and removed controller dir

.github/workflows/build-deploy-backend.yml, .github/workflows/build-deploy-frontend.yml
Want to not use a personal access token to deploy to SKIP.
Removes the use of a personal access token and instead uses OctoSTS to update image-url in [skvis-apps](https://github.com/kartverket/skvis-apps). Also configure the workflows to trigger on `workflow_dispatch` with the option of choosing which commit to deploy and which deployment environments to deploy to. The workflows currently only supports deploying to dev.
Resolves non-existing issue
=> Update deploy workflows

frontend/beCompliant/src/components/tableActions/TableActions.tsx
The filters are resetting on page refresh.
Filters are now saved to localstorage to keep the settings after page refresh
#189
=> keep filters after page refresh

frontend/beCompliant/src/hooks/useFetchTable.ts
Kontrollerdataen refetcher hver gang vinduet får fokus, og hvis man navigerer til en annen route, og så tilbake. Det er unødvendig, siden dataen ikke er så dynamisk, og lastetiden er lang.
Tanstack query har noen enkle verdier man kan sette for å styre cachingen. `refetchOnWindowFocus` er et flagg som sier om dataen skal lastes inn på nytt når vinduet får fokus. Det er default `true`, så setter den til `false`. Setter også `refetchOnMount` til `false` for å forhindre refetching når man navigerer bort og tilbake.
Resolves #195
=> Avoid refetching table data so eagerly

frontend/beCompliant/.env.production
Want to inject `VITE_BACKEND_URL` and `VITE_FRONTEND_URL` instead of building the base-image with values from `.env.production`.
Deletes `.env.production` and instead injects the correct environment variables in [skvis-apps](https://github.com/kartverket/skvis-apps/blob/main/applications/regelrett-frontend.libsonnet).
=> Delete .env.production to use injected env-vars instead

frontend/beCompliant/src/components/tableActions/TableActions.tsx
Hvis man bare har ett aktivt filter, og prøver å nullstille den, så blir ikke det husket når man laster inn siden på nytt.
Fjerner koden som sjekker om aktivefiltre er tom. Ødelegger jeg noe annet ved å gjøre det? Ser ikke sånn ut i min testing 🤔
=> Fix not being able to reset filters

backend/src/main/kotlin/no/bekk/authentication/Authentication.kt
Session cookien utløper etter seks minutter, samme hva. Selv om du trykker deg rundt i appen og gjør nettverkskall blir man fortsatt kastet ut når tokenet utløper.
Legger på en intercept på alle nettverkskall som resetter cookien. Da får man en "sliding expiration"
Resolves #192
=> Refresh session cookie every request

backend/src/main/kotlin/no/bekk/services/MicrosoftService.kt
The prod app-registration in Microsoft Entra ID only has the API Permission `GroupMember.Read.All` towards Graph API, so the backend is unable to request an obo-token successfully with the scope "Group.Read.All" in prod.
The solution is to set the scope to `GroupMember.Read.All` as this is the narrowest scope we need to access group information of the logged in user. I also added this scope on your local Entra ID tenant, so it should not break the local development experience. 
=> Update scope when requesting obo-token

.github/workflows/build-deploy-backend.yml, backend/Dockerfile, backend/build.gradle.kts
Migration scripts are not picked up correctly when starting the application only from the jar. Flyway has an issue on it, and several others experience the same [issue](https://github.com/flyway/flyway/issues/3811)
According to the issue, a fix is to include the shadowJar-plugin and configure it with `mergeServiceFiles()` task. I do not know the details of the solution, but it's worth a shot.
=> Trying build with shadowJar

frontend/beCompliant/src/utils/tablePageUtil.ts
bare første verdien dersom det var flere ble tatt hensyn til i filtrering. Dette førte til at dersom man filtrerte på "hvem" ble bare første verdien "sett på". F.eks. har AR-006 både IT og plattformteam. Dersom man filtrerte på IT ville den vises, men ble borte hvis man filtrerte på plattformteam.
Endret filterData funksjonen til å sjekke om en av verdiene matcher i stedet for å kun ta hensyn til `value[0]`
#193
=> fix multiselect when filtering

backend/src/main/kotlin/no/bekk/model/internal/Table.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt, frontend/beCompliant/src/api/types.ts, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/components/tableActions/TableFilter.tsx, frontend/beCompliant/src/pages/ActivityPage.tsx
Fargene på de ulike alternativene fra airtable var ikke tatt med og vist
Endret til å sende med fargene når tabellen fetches i frontend
Mapper ut riktig farge til alternativet og displayer det
#168
=> add colors to alternatives

frontend/beCompliant/src/components/table/pagination/PaginationButtonContainer.tsx
Viewen hoppet når man byttet sider
Viewen på siden "låses" til nederst i siden uavhengig av lengden på sikkerhetskontrollere. Man kan nå enkelt trykke seg gjennom sidene uten å måtte flytte på pekeren. 
#220
=> fix pagination

frontend/beCompliant/src/components/table/DataTable.tsx, frontend/beCompliant/src/components/table/DataTableHeader.tsx
Når det er sortert på en kolonne og den kolonnen blir skjult, er dataen fortsatt sortert på den kolonnen
Fjerner sortering på kolonnen når kolonnen skjules.
#227
=> Remove sorting when column is hidden

backend/README.md, backend/src/main/resources/application.yaml
Oppdaterer readme med info om hvor man finner secretene man må sette som miljøvariabler.
Gjorde det og mulig å overstyre DB_URL på samme måte som brukernavn og passord, dette for å støtte at man kan kjøre opp databasen lokalt på en annen port enn default (og unngå konflikt med andre postgres-instanser man kan ha kjørende)
=> Updating readme with info about where to find secrets

frontend/beCompliant/src/App.tsx, frontend/beCompliant/src/hooks/useIsLoggedIn.ts
Hvis tokenet til brukeren utløper, så får man ingen respons på det med mindre man laster in siden på nytt. Da kan man avgi svar eller skrive en kommentar, og bare få feilmelding uten å vite at det er fordi man ikke lenger er logget inn.
Har laget en hook som querier `/auth-status` hver gang vinduet får fokus eller komponenten mounter. Da vil man bli redirected til login hvis man har blitt logget ut.
Resolves #225
=> Redirect user to login if not authenticated

backend/resources/.gitignore, backend/resources/airtable.http, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/Comment.tsx, frontend/beCompliant/src/components/table/DataTable.tsx, frontend/beCompliant/src/components/table/DeleteCommentModal.tsx, frontend/beCompliant/src/components/table/TableState.tsx, frontend/beCompliant/src/hooks/useDeleteComment.ts
Om man åpnet en eller flere kontrollere for å skrive kommentar og så endret svaralternativ i en av dropdownene så ble kommentarfeltet lukket. Årsaken til at dette skjedde var at Reac-table er litt teit å mounter komponentene på nytt når data i tabelen endrer seg. Dette betyr at all intern state for en komponent blir glemt. 
For å løse dette er den enkleste løsninge og rett og slett gjøre denne type state mer global. For å ha en form for abstraksjon innførte jeg derfor en `TableStateContext` som kan brukes til å holde på alt av intern state for tabellen. Og så lagrer jeg intern-state i denne contexten slik at man kan bruke `useTableState` eller `useKommentarCellState` for å hente ut staten og eventuelt endre på den. Siden dette ligger globalt utenfor selve tabellen vil den ikke resettes …
=> Fikser at kommentarfeltet lukker seg om man endrer svaralternativ

frontend/beCompliant/src/components/Table.tsx
Om data i tanellen endret seg ble paginering og andre slikt valg reset, som er defaultoppførsel i react-table. Men det skapte litt rar opplevelse slik vi brukte tabellen.
Setter `autoResetAll: false` for å skru av denne defaultoppførselen.
Resolves #247
=> Dont autoreset all table-setting on datachange

frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/TableSort.ts
Sortering for enkelte kolonner blir litt merkelig om man sorterer alfabetisk. F.eks. for ledetid burde det sorteres kort -> middels -> lang (men alfabetisk blir det kort -> lang -> middels). Samme utfordring for prioritet.
Jeg legger til spesialhåndtering av sortering for enkelte kolonner. Dette er desverre ikke veldig fleksibel løsning, men en veldig enkel løsning. På sikt kan man vurdere om man skal gå for noe mer fleksibelt hvor man kan gi en "sortValue" eller noe fra backend, slik at sorteringen kan styres i airtable. Men gjør det enkelt i første omgang med å bare ha spesialhåndtering.
Resolves #165
=> Special sort for some columns

backend/src/main/kotlin/no/bekk/model/internal/Table.kt, backend/src/main/kotlin/no/bekk/services/AirTableService.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt, frontend/beCompliant/src/api/types.ts, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/components/tableActions/TableActions.tsx, frontend/beCompliant/src/pages/ActivityPage.tsx
Navnet `Field` kan være litt tvetydig, og kan gjøre det vanskeligere å forstå hva det skal representere.
Velger å rename den til `Column`, da det mer presist beskriver hva det faktisk er
=> Rename field to column

backend/src/main/kotlin/no/bekk/domain/AirtableResponseMapper.kt, backend/src/main/kotlin/no/bekk/model/internal/Question.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt, frontend/beCompliant/src/api/apiConfig.ts, frontend/beCompliant/src/api/types.ts, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/components/table/TableStatistics.tsx, frontend/beCompliant/src/hooks/useFetchAnswers.ts, frontend/beCompliant/src/hooks/useFetchComments.ts, frontend/beCompliant/src/hooks/useSubmitAnswers.ts, frontend/beCompliant/src/pages/ActivityPage.tsx, frontend/beCompliant/src/utils/mapperUtil.ts, frontend/beCompliant/src/utils/tablePageUtil.ts
Kommentarer og svar fetches sammen med tabellen i frontend. Dette gjør det er vanskelig med caching og oppdatering av states.
Kommentarer og svar fetches fra egne endepunkter. Dataen settes deretter sammen når tabellen skal vises.
Fikk det til å funke ved å endre fra answer til Svar i Answer-typen. Tenker å heller lage en annen task til å rename fra Svar til answer, blir fort mye kluss her.
#243
=> separated answers and comments from table data

frontend/beCompliant/src/components/table/TableStatistics.tsx
Dersom man legger til et svar og deretter fjerner det, står det på statistikkhjulet at spørsmålet er besvart. Det er fordi at det kun sjekkes om det blir lagt til et nytt object i answers.
La til en sjekk for å sjekke om det siste svaret som har blitt lagt til er en tom streng og har dermed egentlig ikke noe svar. Nå funker det hvis man f.eks endrer fra "ok" til "velg alternativ" så blir det -1 på statistikkhjulet. Samme for fritekstfelt.
#295
=> Fix updating statistics

frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/Comment.tsx
Når man legger til svar eller kommentar, øker timestampen høyden på raden som ser rart ut
La til padding på DataTableCell-komponenten slik at det alltid er plass til timestampen
#248
=> fix timestamp affecting row height

frontend/beCompliant/src/components/table/Comment.tsx
Begge knapperne for kommentar blir i loading state når man oppdaterer kommentar
Setter disabled state istedenfor på avbryt knappen når man opdaterer kommentar
Resolves #300
=> disabled the remove button instead of setting it to loading

frontend/beCompliant/src/components/tableActions/TableActions.tsx, frontend/beCompliant/src/components/tableActions/TableFilter.tsx, frontend/beCompliant/src/hooks/useLocalstorageState.ts, frontend/beCompliant/src/pages/ActivityPage.tsx
Filterne blir lagret og overført selv om man bytter tabell. Det fører til at ingen spm vises i f.eks. i SLA når man setter filtere på sikkerhetskontroller-skjema
Endre til å lagre et map med key tableId og value med filtre i stedet for å kun lagre filtrene. Da blir filtrene satt for en type skjema kun dukke opp på det skjemaet
Resolves #401
=> use localstorage to save filters for tables

frontend/beCompliant/src/components/questionPage/QuestionHistory.tsx
Når svaret er tomt, vises uniten (%, min osv) fortsatt i historikk-komponenten. 
La til at uniten kun vises hvis svaret eksisterer
Resolves #461
=> remove unit when no answer in history

backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt, backend/src/main/kotlin/no/bekk/database/CommentRepository.kt, backend/src/main/kotlin/no/bekk/database/DatabaseContext.kt, backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt, frontend/beCompliant/src/api/apiConfig.ts, frontend/beCompliant/src/components/createContextPage/CopyContextDropdown.tsx, frontend/beCompliant/src/hooks/useFetchTeamTableContexts.ts, frontend/beCompliant/src/hooks/useSubmitContext.ts, frontend/beCompliant/src/pages/CreateContextPage.tsx, frontend/beCompliant/src/pages/LockedCreateContextPage.tsx, frontend/beCompliant/src/pages/UnlockedCreateContextPage.tsx
=> kopier svar fra annet skjema

frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx, frontend/beCompliant/src/components/answers/PercentAnswer.tsx, frontend/beCompliant/src/components/answers/TimeAnswer.tsx, frontend/beCompliant/src/components/questionPage/LastUpdatedQuestionPage.tsx, frontend/beCompliant/src/components/questionPage/QuestionAnswer.tsx, frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx, frontend/beCompliant/src/components/questionPage/RadioAnswer.tsx, frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/pages/QuestionPage.tsx
Dersom tekstfelter har dobbel linjeskift skal kun teksten fra til linjeskift vises i tabellen, men hele teksten skal vises på spørsmålssiden.
- La til håndtering av linjeskift. Testet med testskjemaet. La til linjeskift og tekst i beskrivelsen til AR-001 hvis dere vil teste
- Måtte endre litt på spørsmålssiden slik at det ser noenlunde greit ut
Resolves #488
=> handle line breaks and fix question page layout

frontend/beCompliant/src/components/table/TableCell.tsx
Beskrivelsesfeltet blir veldig langt (spesielt i SLA) som gjør det litt vanskelig å lese
La til maxWidth for å gjøre den smalere
Resolves #496
=> add maxWidth to text columns

.github/workflows/build-deploy-backend-gcp.yml
GCP VM disk space blir ofte tom fordi den fylles opp med gamle docker images.
Legge på en cleanup i workflowen som sletter dangling images.
#506
=> removing dangling images

frontend/beCompliant/src/components/table/DataTable.tsx
Borderen rundt radene synes ikke på stor skjerm
Økte størrelsen til 2px slik at den synes uansett skjermstørrelse
Endret fra border til outline slik at radene ikke "hopper" når man hovrer
Resolves #522
=> change border to outline and increase size

backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt
Hvis det var komma i et av feltene tolket csv filen det som en ny kolonne. Endret til at hvert felt blir wrappet i double quotes.
#533
=> fix comma in string bug csv export

frontend/beCompliant/src/utils/tablePageUtil.ts
Hvis man filterer på svar, går til front page, refresher, og prøver å gå inn på skjemaet inn kastes det en exception.
Fant ut at record.answers kan være undefined i noen tilfeller når data filtreres, og at det er derfor feilmeldingen om .at() kastes.
La til en sjekk som sjekker at det faktisk er en array.
Resolves #530
=> bug: .at() exception when refreshing

frontend/beCompliant/src/components/questionPage/QuestionComment.tsx
Doble linjeskift synes ikke på detaljsiden
whitespace: normal -> pre-wrap
Resolves #560
=> fix linjeskift on comments in detailed view

.github/workflows/build-deploy-backend-gcp.yml, backend/src/main/kotlin/no/bekk/Application.kt, backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt, backend/src/main/kotlin/no/bekk/model/internal/Table.kt, backend/src/main/kotlin/no/bekk/plugins/Cors.kt, backend/src/main/kotlin/no/bekk/plugins/Routing.kt, backend/src/main/kotlin/no/bekk/providers/AirTableProvider.kt, backend/src/main/kotlin/no/bekk/providers/TableProvider.kt, backend/src/main/kotlin/no/bekk/providers/YamlProvider.kt, backend/src/main/kotlin/no/bekk/routes/TableRouting.kt, backend/src/main/resources/application.yaml, frontend/beCompliant/src/pages/CreateContextPage.tsx
- lagde /schemas endepunkt for å ikke få med unødvendig data fra /tables endepunktet
- flyttet /tables endepunktet tilbake til TableRouting
- endret på "redirect" i frontend for at det skal matche med ny skjema-metadata
- la til frisk frontend url i config slik at endepunktene kan kalles på fra frisk
Resolves 191 i frisk
=> add get schemas endpoint, fix cors frisk, fix redirect for new metadata

backend/src/main/kotlin/no/bekk/Application.kt, backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt, backend/src/main/resources/application.yaml
Reverts kartverket/regelrett#586
=> Revert "547 gjøre tables config basert"

backend/src/main/kotlin/no/bekk/Application.kt, backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt, backend/src/main/resources/application.yaml
Ønske om å kunne konfigurere opp tables
Tables i `application.yaml` har en liste `tables` som `Application.kt` iterer igjennom og gjør om til en liste med `AirTableInstanceConfig` og `YAMLInstanceConfig`. Så iterer `TableService.kt` igjennom tables.tables for å opprette providers. 
Resolves [547](https://github.com/orgs/kartverket/projects/16/views/1?pane=issue&itemId=90652606&issue=kartverket%7Cregelrett%7C547)
=> Regelrett config

frontend/beCompliant/src/components/Table.tsx
Byttet fra expand ikon til info ikon på "se mer" knappen
=> Tydeligere ikon for se mer knappen

frontend/beCompliant/src/components/table/SettingsModal.tsx
Brukertest viste at settings-modalen på skjemaet var vanskelig å forstå. Endret til at det er egne tabs for forskjellige settings.
#600
=> refactor settings modal with tabs

backend/src/main/kotlin/no/bekk/Application.kt, backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt, backend/src/main/kotlin/no/bekk/database/ContextRepository.kt, backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt, backend/src/main/kotlin/no/bekk/services/TableService.kt, backend/src/main/resources/application.yaml, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/answers/CheckboxAnswer.tsx, frontend/beCompliant/src/components/answers/PercentAnswer.tsx, frontend/beCompliant/src/components/answers/SingleSelectAnswer.tsx, frontend/beCompliant/src/components/answers/TextAnswer.tsx, frontend/beCompliant/src/components/answers/TimeAnswer.tsx, frontend/beCompliant/src/components/table/AnswerCell.tsx, frontend/beCompliant/src/components/table/SettingsModal.tsx, frontend/beCompliant/src/components/table/TableCell.tsx, frontend/beCompliant/src/hooks/useFetchContext.ts, frontend/beCompliant/src/pages/ActivityPage.tsx
=> Staging -> main

.security/risc/.sops.yaml
This pull request updates the SOPS configuration that is needed to encrypt and decrypt RiSc's in [Risk Scorecard in Kartverket.dev](https://kartverket.dev/catalog/default/component/regelrett/risc). Merge this PR in order to use the new SOPS configuration in the [Risk Scorecard plugin](https://kartverket.dev/catalog/default/component/regelrett/risc).
=> Update SOPS configuration

frontend/beCompliant/src/components/answers/PercentAnswer.tsx, frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx, frontend/beCompliant/src/components/table/LastUpdated.tsx
Bruker skjønte ikke hva iconet for å fornye svaret var. Mål: gjøre knappen tydligere
Gjorde icon-button om til en button med telsten Forny svar.
(måtte også gjør om background til backgroundColor i textAreaAnswer pga warning fra intellij. 
Resolves [#605](https://github.com/kartverket/regelrett/issues/605)
=> 605 utforske nytt ikon for oppdater svar

frontend/beCompliant/src/components/table/DataTable.tsx
Forsøk på å fikse bug: Hvis du åpner et skjema fra frisk vil og så et nytt ett vil deltaljert-visning switchen huske siste skjema sin switch state - uavhengig av filtrerte kolonner som huskes per skjema av regelrett. 
Fjernet unødvendig bruk av state - isDetailedview initieres til å være `!hasHiddenColumns` og den er basert på er en state, så da trenger man den ikke for å trigge rerendering.
=> 616 bug toogle deltaljert visning

frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/DataTable.tsx, frontend/beCompliant/src/hooks/useColumnVisibility.ts
Jobis toggle detaljert visning mellom skjema bugs. Viste seg at det ble kluss fordi sikkerhetsskjema fikk det andre skjematrtpen sine kolonner opp i "skjulte kolonner" og vica versa. 
Slettet `hasHiddenColumns` og byttet den ut med `table.getIsAllColumnsVisible()` for å få riktig oppdatering av skjulte kolonner per skjema. i tilegg, isdet for å iterer over headers i local-storage variabelen burker jeg heller visiblecolumns. DeleteColumns måtte også oppderees slik at den ikkke satte alle headers i alle skjema til visible, men heller kun de som gjelder skjeamet man er inne i. 
=> Toggle detaljertvisning bug

frontend/beCompliant/src/components/questionPage/QuestionComment.tsx, frontend/beCompliant/src/components/table/Comment.tsx
Shift + return i kommentarfelt submittet kommentaren. Fra tilbakemeldinger var det ønsket at det heller skulle være en soft return.
**Løsning**
🆕 Endring: 
Fjernet fra handleKeyDown() i kommentar-komponentene
**🧪 Testing**
Resolves #620
=> remove submit comment with shift return

frontend/beCompliant/src/pages/FrontPage.tsx
Vise at skjemautfyllinger holder på laste inn slik at brukeren vet at det finnes noen
**Løsning**
🆕 Endring: 
La til bredde og høyde til skeleton for at den skal vises, og endret til "&&" i isLoaded slik at den forsvinner når alt faktisk er lastet inn.
**🧪 Testing**
Resolves #633
=> fix team contexts skeleton

backend/src/main/kotlin/no/bekk/database/ContextRepository.kt, backend/src/main/kotlin/no/bekk/plugins/Routing.kt
OBS: kan merges etter at PR 109 i FRISK er merged
Fjerne endepunktet som ble brukt til skjema-metadata migrering i Frisk
**Løsning**
🆕 Endring: 
slettet endepunktet
**🧪 Testing**
Resolves #637
=> remove unused schema migration endpoint

backend/src/main/kotlin/no/bekk/Application.kt, backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt, backend/src/main/kotlin/no/bekk/database/CommentRepository.kt, backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt, backend/src/main/resources/application.yaml, backend/src/main/resources/db/migration/V13__add_comments_constraint.sql, frontend/beCompliant/src/components/questionPage/QuestionComment.tsx, frontend/beCompliant/src/components/table/Comment.tsx, frontend/beCompliant/src/components/table/DeleteCommentModal.tsx, frontend/beCompliant/src/hooks/useComments.ts
- Faktisk fjerne data og ikke bare la det bli liggende i DB
**Løsning**
🆕 Endring: 
- Kommentarer blir faktisk slettet når de slettes i UI (før ble bare en tom rad lagt til i DB)
- Hvis en kommentar endres så endres comment-kolonnen på den samme raden i DB (Før ble en ny rad lagt til i DB)
- Lagt til en cleanup job som sletter svar hver 4. uke (kan konfigureres), da slettes alle svar bortsett fra de 3 nyeste. Den ser på context_id og record_id for å ta hensyn til både skjemautfyllingen og spørsmålet.
**🧪 Testing**
Kan kjøre opp lokalt og se at DB endringene blir riktig
- Trengs det noen sikkerhetstiltak eller …
=> fix comment and answer cleanup in database

frontend/beCompliant/src/api/apiConfig.ts, frontend/beCompliant/src/hooks/useUser.ts
QueryKey til å fetche usename manglet userId som førte til at den bare hentet fra cache i stedet for å hente username når userId endret seg
**Løsning**
🆕 Endring: 
La til userId i querykey'en
**🧪 Testing**
=> fix querykey in useFetchUsername

frontend/beCompliant/src/components/questionPage/QuestionComment.tsx, frontend/beCompliant/src/components/table/Comment.tsx
Rydde oppi knappene til å redigere kommentarer etter skisser
**Løsning**
🆕 Endring: 
Flyttet knappene til å være under kommentaren
Endret redigerings- og sletteknapp til å ha ikon og label
Endret lagre- og avbrytknapp i redigeringsmodus til å kun ha label
**🧪 Testing**
Resolves #656
=> change edit comment buttons

frontend/beCompliant/src/components/table/SettingsModal.tsx, frontend/beCompliant/src/pages/ActivityPage.tsx
Tydeligere tilbakemelding til brukeren når team på skjema skal endres.
**Løsning**
🆕 Endring:
- La til teamet til skjemautfyllingen øverst på siden
- La til teamnavn i redigeringsboksen
- Endret feilmeldingen fra toast til rød border + tekst under dersom brukeren skriver inn feil teamnavn
- Modalen lukkes og en toast dukker opp hvis teamet endres
- Småendringer på tekst i redigeringsboksen fra skissene
**🧪 Testing**
Resolves #650
=> Improve team change in settings modal

frontend/beCompliant/src/components/CSVDownload.tsx, frontend/beCompliant/src/components/Table.tsx, frontend/beCompliant/src/components/table/DataTable.tsx, frontend/beCompliant/src/components/table/DataTableSearch.tsx, frontend/beCompliant/src/pages/ActivityPage.tsx
Fikse litt opp i layouten på skjemautfylling etter skissene til Magnus
**Løsning**
🆕 Endring: 
- Lagt til ikon på “last ned CSV”-knappen
- Nytt design på detaljert visning-switch. Forenklet med beskrivelsen "Vis alle kolonner"
- Flytte søkefelt over filtre, og legge til label “Søk i tabell”
- Overskriften og progress-sirkelen er nå på samme linje som innholdet under divideren
Før:
Etter:
**🧪 Testing**
Resolves #648
=> some layout changes

frontend/beCompliant/Dockerfile
🥅 Mål med PRen: Bumper libxml2 for å fikse sårbarheter oppdaga av Pharos
**Løsning**
🆕 Endring: Oppdaterer libxml2 til spesifikk versjon med fix for de oppdaga sårbarhetene. Pinner image for å holde image litt mer stabilt, slik at den ikke plutselig oppdaterer libxml2 til noe helt annet uten at vi velger det.
**🧪 Testing**
=> Upgrade libxml2 to fix vulnerabilities

.github/workflows/build-deploy-backend-gcp.yml, backend/Dockerfile, backend/src/main/kotlin/no/bekk/Application.kt, backend/src/main/kotlin/no/bekk/authentication/Authentication.kt, backend/src/main/kotlin/no/bekk/configuration/AppConfig.kt, backend/src/main/kotlin/no/bekk/configuration/DbConfiguration.kt, backend/src/main/kotlin/no/bekk/plugins/Cors.kt, backend/src/main/kotlin/no/bekk/plugins/FlywayMigrate.kt, backend/src/main/kotlin/no/bekk/plugins/Routing.kt, backend/src/main/kotlin/no/bekk/providers/clients/AirTableClient.kt, backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt, backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt, backend/src/main/kotlin/no/bekk/services/FormService.kt, backend/src/main/kotlin/no/bekk/services/MicrosoftService.kt
Begrense CORS og gjøre det konfigurerbart
**Løsning**
🆕 Endring: 
- La til CORS konfigurering for gcp og skip
- Refaktorerte AppConfig og Application for å gjøre det enklere å sende inn config og starte refaktoring fra singletons og til å supporte injection pattern. Førte til litt endringer i andre filer. 
OBS: Instantiering av configen til FormService og MicrosoftService i module() vil fjernes etter at de er gjort om til klasser. "by lazy" som ble lagt til i FormService vil også gå bort. Gjorde det sånn nå for å minimere PR'en. 
**🧪 Testing** …
=> limit cors and start refactoring from singleton

frontend/beCompliant/src/pages/ActivityPage.tsx
🥅 Mål med PRen: 
Ved endring av navn på kolonne i airtable forble et ugyldig filtenavn i localstorage, og filteret gikk sin gang og fant ingen rader som tilfredstilte ekstisterende løsning.
**Løsning**
🆕 Endring: 
Lagt til en sjekk på at de lagrede filterene i local storage; hvis filter ikke tilsvarer kolonnenavn så fjernes det fra `activeFilters`
Dette er ikke en optimal løsning, så har laget enda en ticket på å løse litt opp i spaghettien som gjelder å styre med url filtere og local storage filtere. Den ligger foreløpig i blocked.
=> 675 bug sikkerhetskontroller skjema er tomt

backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt, backend/src/main/kotlin/no/bekk/database/CommentRepository.kt
Manglet en sjekk på om svar eller kommentarer man skal kopiere fra et skjema er tomme, som gjorde at insert feilet. La til fiks
=> Hvis svar eller kommentarer er tomme, skip insert i db

frontend/beCompliant/src/components/TeamContexts.tsx, frontend/beCompliant/src/pages/FrontPage.tsx
fix: visual bug på frontPage forårsaket av lange contextnavn
fix: wrap columns til en rad på mindre skjermer
Før
Etter
=> 756 Visningsbug på regelrett frontpage

frontend/beCompliant/src/components/table/DataTable.tsx, frontend/beCompliant/src/hooks/useColumnVisibility.ts
Når man manuelt skjulte en av kolonnen i tabellen som ikke skjules av switchen (aka utfylingsmodus kolonnen svar, id etc), så fikk man ikke un-hidet de med switchen. 
**Løsning**
🆕 Endring: 
fjernet en sjekk som fohindret unhide av kolonner som var i utfyllingsmoduskolonne indeks lista. 
Mens jeg var i gang forenklet jeg onchange til inline. 
**🧪 Testing**
test godt funkskjonelt.
Man kan manuelt hide alle kolonenne i tabellen. er det ønskelig?
Vi er i denne seksjonen visuelt i rr:
=> Bug: switchen på vis alle kolonner funker ikke når man unhider en kolonner definert som utfyllingsmodus.

backend/src/main/kotlin/no/bekk/database/AnswerRepository.kt, backend/src/main/kotlin/no/bekk/routes/AnswerRouting.kt, backend/src/main/kotlin/no/bekk/routes/CommentRouting.kt, backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt, backend/src/main/kotlin/no/bekk/routes/FormRouting.kt, backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt, backend/src/main/kotlin/no/bekk/routes/UserInfoRouting.kt, backend/src/test/kotlin/no/bekk/database/AnswerRepositoryTest.kt, backend/src/test/kotlin/no/bekk/routes/AnswerRoutingTest.kt, backend/src/test/kotlin/no/bekk/routes/MockAnswerRepository.kt
Alle svarene hentes ut i tabellvisningen, det er ikke nødvendig da vi kun viser det nyeste svaret og alle svarene blir hentet ut i spørsmålssiden
**Løsning**
🆕 Endring: 
Endret til å kun hente ut de nyeste svarene i tabellvisningen. Vi hadde allerede en metode som gjorde det så fikk forenklet litt og fjernet kode. `getAnswersByContextAndRecordIdFromDatabase` ble ikke endret da det er det som henter ut svar til spørsmålssiden
**🧪 Testing**
Resolves #776
=> forenkle get answers endepunktet

backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt, backend/src/test/kotlin/no/bekk/routes/ContextRoutingTest.kt
get context på contextId endepunktet returnerer unautherized hvis man ikke er medlem av teamet som eier contexten. Men da sjekken tar til grunnlag at man sender med token for å sjekke opp om man faktisk er meldme av riktig team, er det forbidden som blir riktig respons da dte ikke mangler vedlagt autentisering. De andre endepunktene svarer med forbidden på samme sjekk. 
**Løsning**
🆕 Endring: endre fra Unauthorized til Forbidden 
**🧪 Testing**
Test funksjonaliteten godt lokalt i tillfelle jeg har oversett noe funksjonalitet som er avhengig av 401 feilmelding her.
=> get context by contextId Unauthorized -> Forbidden ved maglende tilgang.

frontend/beCompliant/src/pages/activityPage/ActivityPage.tsx
Frontenden kastet error state på at du mangler tilgang til contexten på statuskode 401 - dette skal være 403, ettersom det ble rettet opp i backenden.
=> 401 -> 403 ved forbidden request

backend/src/main/kotlin/no/bekk/routes/UploadCSVRouting.kt
Når man eksporterer alle skjemaene i regelret så tar man nyeste versjonen av et gitt svar. Om et svar har historikk så vil det derfor uansett komme med, selv om nyeste versjonen er tomt / slettet. Et siste steg i sql-uttrekket bør derfor være å fjerne null-svar så de ikke kommer med.
=> Fjern null og tomme svar når man eksporterer skjemaene

backend/src/main/kotlin/no/bekk/routes/ContextRouting.kt, backend/src/test/kotlin/no/bekk/routes/ContextRoutingTest.kt, frontend/beCompliant/src/hooks/useContext.ts
Frisk sender med teamId for å endre en skjemautfylling (context) sitt team, mens regelrett-frontenden sender teamname for å ikke være begrenset av team en selv er medlem av. 
**Løsning**
🆕 Endring:
For å tillate frisk å kunne endre teamet til skjemautfyllingen, aksepterer patch-endepunktet enten en teamId eller teamcontext. 
I tillegg hadde regelrett-endreteam-hooken feil URL - så slang på /team
**🧪 Testing**
=> accept either teamname or teamid in context team patch

frontend/beCompliant/src/components/ui/sonner.tsx, frontend/beCompliant/src/pages/frontPage/ContextLink.tsx, frontend/beCompliant/src/pages/frontPage/DeleteContextModal.tsx, frontend/beCompliant/src/styles.css
🥅 Mål med PRen: Minske trykkflaten for slett-skjemaløsningen, og forbedre designet.
**Løsning**
🆕 Endring: 
- Minsket slett-teksten til en liten knapp til venstre for overskriften. 
- Lagt på sist-endret dato på skjemautfyllings-kortet
- Lagt til toast ved sletting
- Lagt til navn på skjema og skjemautfylling i slett-dialogen. 
- Endret hoverfargen til litt mer blå.
Mer detaljert beskrivelse: 
Det er veldig enkelt å ved en feil trykke på «Slett skjematufylling» på oversiktsiden til Regelrett i dag, når man egentlig skal inn på et skjema. Det er ikke helt kritisk, siden man uansett må bekrefte sletting, men kan være ganske irriterende.
Vi endrer derfor til en ghost-knapp slik at området for å slette blir mye mindre. Vi legger samtidig til dato for når skjemaet sist ble …
=> 831 unngå at brukere trykker på slett skjemautfylling ved en feil

frontend/beCompliant/src/pages/activityPage/ActivityPage.tsx, frontend/beCompliant/src/pages/activityPage/TableStatistics.tsx, frontend/beCompliant/src/pages/activityPage/table/DataTable.tsx, frontend/beCompliant/src/pages/activityPage/table/Table.tsx
Brukere har ingen god måte å se fremgangen på utfylte svar basert på de aktive filtrene de har valgt.
**Løsning**
Legger til en bryter slik at man kan toggle mellom å se fremgang for hele skjemaet, eller for de radene som vises basert på aktive filtre. Lagrer valget i localstorage slik at man slipper å endre på det hver gang.
Resolves #793
=> Oppdatere ui på filtrerte svar
